In [255]:
# !pip install boto3 python-dotenv

In [256]:
# from dotenv import load_dotenv
# import os

# load_dotenv()

# import boto3

# s3 = boto3.client("s3")

In [257]:
# Instalar a biblioteca unidecode para remover acentos
!pip install unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.12/dist-packages (1.4.0)

In [258]:
# Install necessary libraries
!pip install geopandas openpyxl

Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (26.1)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2026.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2026.4.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [259]:
import geopandas as gpd
import io

# # Define the input GeoJSON file path
# s3 = boto3.client("s3")
# bucket_name = "s3rawgrupo7"
# object_key = "geoportal_distrito_municipal_v2.geojson"

# response = s3.get_object(
#     Bucket=bucket_name,
#     Key=object_key
# )

# conteudo = response["Body"].read()

# gdf_distrito = gpd.read_file(io.BytesIO(conteudo))

# object_key = "geoportal_subprefeitura_v2.geojson"

# response = s3.get_object(
#     Bucket=bucket_name,
#     Key=object_key
# )


# gdf_subprefeitura = gpd.read_file(io.BytesIO(response["Body"].read()))

# Define the input GeoJSON file path
geojson_distrito_file_path = '/content/geoportal_distrito_municipal_v2.geojson'
geojson_subprefeitura_file_path = '/content/geoportal_subprefeitura_v2.geojson'

# Read the GeoJSON file into a GeoDataFrame
gdf_distrito = gpd.read_file(geojson_distrito_file_path)
gdf_subprefeitura = gpd.read_file(geojson_subprefeitura_file_path)

# Display the first few rows and information about the GeoDataFrame
print("GeoDataFrame head:")
display(gdf_distrito.head())
print("\nGeoDataFrame info:")
gdf_distrito.info()

# Display the first few rows and information about the GeoDataFrame
print("GeoDataFrame head:")
display(gdf_subprefeitura.head())
print("\nGeoDataFrame info:")
gdf_subprefeitura.info()

GeoDataFrame head:

,id,cd_identificador_distrito,cd_identificador_subprefeitura,cd_distrito_municipal,nm_distrito_municipal,sg_distrito_municipal,tx_escala,sg_fonte_original,dt_criacao,dt_atualizacao,cd_usuario_atualizacao,cd_tipo_discrepancia,qt_area_quilometro,qt_area_metro,cd_regiao_05,nm_regiao_05,cd_regiao_08,nm_regiao_08,geometry
0,distrito_municipal_v2.8583410,8583410,21,67,RIO PEQUENO,RPE,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.005000+00:00,None,199299399,9.657,9657007.38,4,Oeste,6,Oeste,"POLYGON ((320567.464 7394377.312, 320581.184 7..."
1,distrito_municipal_v2.8583465,8583465,30,25,CIDADE TIRADENTES,CTI,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.006000+00:00,None,199299399,14.939,14939046.96,2,Leste,3,Leste 2,"POLYGON ((357428.688 7387653.528, 357433.497 7..."
2,distrito_municipal_v2.8583484,8583484,24,46,JARDIM SAO LUIS,JDS,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.008000+00:00,None,199299399,26.048,26047523.11,5,Sul,8,Sul 2,"POLYGON ((321618.419 7377778.152, 321559.629 7..."
3,distrito_municipal_v2.8583407,8583407,8,64,PONTE RASA,PRA,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.010000+00:00,None,199299399,6.597,6596680.61,2,Leste,3,Leste 2,"POLYGON ((344730.886 7398738.087, 344738.505 7..."
4,distrito_municipal_v2.8583488,8583488,14,49,LIBERDADE,LIB,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.011000+00:00,None,199299399,3.651,3651129.57,1,Centro,1,Centro,"POLYGON ((332504.514 7392094.984, 332505.952 7..."

GeoDataFrame info:
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              96 non-null     object
 1   cd_identificador_distrito       96 non-null     int32
 2   cd_identificador_subprefeitura  96 non-null     int32
 3   cd_distrito_municipal           96 non-null     object
 4   nm_distrito_municipal           96 non-null     object
 5   sg_distrito_municipal           96 non-null     object
 6   tx_escala                       96 non-null     object
 7   sg_fonte_original               96 non-null     object
 8   dt_criacao                      96 non-null     datetime64[ms]
 9   dt_atualizacao                  96 non-null     datetime64[ms, UTC]
 10  cd_usuario_atualizacao          0 non-null      object
 11  cd_tipo_discrepancia            96 non-null     int32
 12  qt_area_quilometro              96 non-null     float64
 13  qt_area_metro                   96 non-null     float64
 14  cd_regiao_05                    96 non-null     int32
 15  nm_regiao_05                    96 non-null     object
 16  cd_regiao_08                    96 non-null     int32
 17  nm_regiao_08                    96 non-null     object
 18  geometry                        96 non-null     geometry
dtypes: datetime64[ms, UTC](1), datetime64[ms](1), float64(2), geometry(1), int32(5), object(9)
memory usage: 12.5+ KB
GeoDataFrame head:

,id,cd_identificador_subprefeitura,cd_subprefeitura,nm_subprefeitura,tx_escala,sg_fonte_original,dt_criacao,cd_tipo_discrepancia,dt_atualizacao,cd_usuario_atualizacao,sg_subprefeitura,qt_area_quilometro,qt_area_metro,cd_regiao_05,nm_regiao_05,cd_regiao_08,nm_regiao_08,geometry
0,subprefeitura_v2.26,26,16,CIDADE ADEMAR,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.317000+00:00,,AD,31,30810241.77,5,Sul,8,Sul 2,"POLYGON ((332383.832 7381216.079, 332408.532 7..."
1,subprefeitura_v2.24,24,18,M BOI MIRIM,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.340000+00:00,,MB,62,62411386.53,5,Sul,8,Sul 2,"POLYGON ((316695.723 7378199.471, 316704.833 7..."
2,subprefeitura_v2.15,15,25,MOOCA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.342000+00:00,,MO,36,36046910.58,2,Leste,2,Leste 1,"POLYGON ((334126.109 7396389.068, 334125.831 7..."
3,subprefeitura_v2.19,19,13,IPIRANGA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.344000+00:00,,IP,37,37497323.00,5,Sul,7,Sul 1,"POLYGON ((335254.612 7391150.376, 335253.982 7..."
4,subprefeitura_v2.13,13,08,LAPA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.345000+00:00,,LA,41,40638699.56,4,Oeste,6,Oeste,"POLYGON ((321633.729 7393535.365, 321633.031 7..."

GeoDataFrame info:
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              32 non-null     object
 1   cd_identificador_subprefeitura  32 non-null     int32
 2   cd_subprefeitura                32 non-null     object
 3   nm_subprefeitura                32 non-null     object
 4   tx_escala                       32 non-null     object
 5   sg_fonte_original               32 non-null     object
 6   dt_criacao                      32 non-null     datetime64[ms]
 7   cd_tipo_discrepancia            32 non-null     int32
 8   dt_atualizacao                  32 non-null     datetime64[ms, UTC]
 9   cd_usuario_atualizacao          32 non-null     object
 10  sg_subprefeitura                32 non-null     object
 11  qt_area_quilometro              32 non-null     int32
 12  qt_area_metro                   32 non-null     float64
 13  cd_regiao_05                    32 non-null     int32
 14  nm_regiao_05                    32 non-null     object
 15  cd_regiao_08                    32 non-null     int32
 16  nm_regiao_08                    32 non-null     object
 17  geometry                        32 non-null     geometry
dtypes: datetime64[ms, UTC](1), datetime64[ms](1), float64(1), geometry(1), int32(5), object(9)
memory usage: 4.0+ KB

### Converter GeoDataFrame para Pandas DataFrame

Para converter o `gdf` (GeoDataFrame) em um DataFrame Pandas padrão, precisamos lidar com a coluna `geometry`. Transformaremos os objetos `geometry` em sua representação Well-Known Text (WKT), que é uma maneira comum de armazenar dados espaciais em formato de texto dentro de um DataFrame regular. Posteriormente, a coluna `geometry` original será removida.

In [260]:
import pandas as pd

# Cria uma cópia do GeoDataFrame para evitar modificar o original
df_pandas_distrito = gdf_distrito.copy()

# Converte a coluna 'geometry' para o formato Well-Known Text (WKT)
df_pandas_distrito['geometry_wkt'] = df_pandas_distrito['geometry'].apply(lambda geom: geom.wkt if geom else None)

# Remove a coluna 'geometry' original, pois não é um tipo padrão do pandas
df_pandas_distrito = df_pandas_distrito.drop(columns=['geometry'])

print("Cabeçalho do DataFrame Pandas (com geometria como WKT):")
display(df_pandas_distrito.head())

print("\nInformações do DataFrame Pandas:")
df_pandas_distrito.info()

Cabeçalho do DataFrame Pandas (com geometria como WKT):

,id,cd_identificador_distrito,cd_identificador_subprefeitura,cd_distrito_municipal,nm_distrito_municipal,sg_distrito_municipal,tx_escala,sg_fonte_original,dt_criacao,dt_atualizacao,cd_usuario_atualizacao,cd_tipo_discrepancia,qt_area_quilometro,qt_area_metro,cd_regiao_05,nm_regiao_05,cd_regiao_08,nm_regiao_08,geometry_wkt
0,distrito_municipal_v2.8583410,8583410,21,67,RIO PEQUENO,RPE,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.005000+00:00,None,199299399,9.657,9657007.38,4,Oeste,6,Oeste,"POLYGON ((320567.4639 7394377.3124, 320581.183..."
1,distrito_municipal_v2.8583465,8583465,30,25,CIDADE TIRADENTES,CTI,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.006000+00:00,None,199299399,14.939,14939046.96,2,Leste,3,Leste 2,"POLYGON ((357428.6884 7387653.528, 357433.4974..."
2,distrito_municipal_v2.8583484,8583484,24,46,JARDIM SAO LUIS,JDS,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.008000+00:00,None,199299399,26.048,26047523.11,5,Sul,8,Sul 2,"POLYGON ((321618.4192 7377778.152, 321559.6291..."
3,distrito_municipal_v2.8583407,8583407,8,64,PONTE RASA,PRA,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.010000+00:00,None,199299399,6.597,6596680.61,2,Leste,3,Leste 2,"POLYGON ((344730.8856 7398738.0871, 344738.505..."
4,distrito_municipal_v2.8583488,8583488,14,49,LIBERDADE,LIB,1:5000,GEOGSG,2004-01-01,2026-03-20 16:13:20.011000+00:00,None,199299399,3.651,3651129.57,1,Centro,1,Centro,"POLYGON ((332504.5145 7392094.9838, 332505.951..."

Informações do DataFrame Pandas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              96 non-null     object
 1   cd_identificador_distrito       96 non-null     int32
 2   cd_identificador_subprefeitura  96 non-null     int32
 3   cd_distrito_municipal           96 non-null     object
 4   nm_distrito_municipal           96 non-null     object
 5   sg_distrito_municipal           96 non-null     object
 6   tx_escala                       96 non-null     object
 7   sg_fonte_original               96 non-null     object
 8   dt_criacao                      96 non-null     datetime64[ms]
 9   dt_atualizacao                  96 non-null     datetime64[ms, UTC]
 10  cd_usuario_atualizacao          0 non-null      object
 11  cd_tipo_discrepancia            96 non-null     int32
 12  qt_area_quilometro              96 non-null     float64
 13  qt_area_metro                   96 non-null     float64
 14  cd_regiao_05                    96 non-null     int32
 15  nm_regiao_05                    96 non-null     object
 16  cd_regiao_08                    96 non-null     int32
 17  nm_regiao_08                    96 non-null     object
 18  geometry_wkt                    96 non-null     object
dtypes: datetime64[ms, UTC](1), datetime64[ms](1), float64(2), int32(5), object(10)
memory usage: 12.5+ KB

In [261]:
from unidecode import unidecode
import re

def remove_accents_and_normalize(text, keep_spaces=False):
    if isinstance(text, str):
        text = unidecode(text).upper()
        # Substitui separadores comuns como '/', '.', ',', etc., por espaços.
        text = re.sub(r'[^\w\s-]', ' ', text) # Mantém alfanuméricos, espaços e hifens

        # Normaliza espaços - substitui múltiplos espaços por um único espaço
        text = re.sub(r'\s+', ' ', text).strip()

        if not keep_spaces:
            # Substitui todos os espaços por hifens, mas apenas se keep_spaces for False
            text = re.sub(r'\s', '-', text)

            # Normaliza hifens - substitui múltiplos hifens por um único hifen
            # e remove hifens iniciais/finais.
            text = re.sub(r'-+', '-', text).strip('-')

        return text
    return text

In [262]:
# Cria uma cópia do GeoDataFrame para evitar modificar o original
df_pandas_subprefeitura = gdf_subprefeitura.copy()

# Converte a coluna 'geometry' para o formato Well-Known Text (WKT)
df_pandas_subprefeitura['geometry_wkt'] = df_pandas_subprefeitura['geometry'].apply(lambda geom: geom.wkt if geom else None)

# Remove a coluna 'geometry' original, pois não é um tipo padrão do pandas
df_pandas_subprefeitura = df_pandas_subprefeitura.drop(columns=['geometry'])

print("Cabeçalho do DataFrame Pandas (com geometria como WKT):")
display(df_pandas_subprefeitura.head())

print("\nInformações do DataFrame Pandas:")
df_pandas_subprefeitura.info()

Cabeçalho do DataFrame Pandas (com geometria como WKT):

,id,cd_identificador_subprefeitura,cd_subprefeitura,nm_subprefeitura,tx_escala,sg_fonte_original,dt_criacao,cd_tipo_discrepancia,dt_atualizacao,cd_usuario_atualizacao,sg_subprefeitura,qt_area_quilometro,qt_area_metro,cd_regiao_05,nm_regiao_05,cd_regiao_08,nm_regiao_08,geometry_wkt
0,subprefeitura_v2.26,26,16,CIDADE ADEMAR,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.317000+00:00,,AD,31,30810241.77,5,Sul,8,Sul 2,"POLYGON ((332383.8317 7381216.0788, 332408.531..."
1,subprefeitura_v2.24,24,18,M BOI MIRIM,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.340000+00:00,,MB,62,62411386.53,5,Sul,8,Sul 2,"POLYGON ((316695.7231 7378199.4713, 316704.833..."
2,subprefeitura_v2.15,15,25,MOOCA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.342000+00:00,,MO,36,36046910.58,2,Leste,2,Leste 1,"POLYGON ((334126.1094 7396389.0681, 334125.831..."
3,subprefeitura_v2.19,19,13,IPIRANGA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.344000+00:00,,IP,37,37497323.00,5,Sul,7,Sul 1,"POLYGON ((335254.6122 7391150.3765, 335253.982..."
4,subprefeitura_v2.13,13,08,LAPA,1:5000,GEOGSG,2023-11-30,100200300,2026-03-20 16:14:01.345000+00:00,,LA,41,40638699.56,4,Oeste,6,Oeste,"POLYGON ((321633.7288 7393535.3646, 321633.031..."

Informações do DataFrame Pandas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              32 non-null     object
 1   cd_identificador_subprefeitura  32 non-null     int32
 2   cd_subprefeitura                32 non-null     object
 3   nm_subprefeitura                32 non-null     object
 4   tx_escala                       32 non-null     object
 5   sg_fonte_original               32 non-null     object
 6   dt_criacao                      32 non-null     datetime64[ms]
 7   cd_tipo_discrepancia            32 non-null     int32
 8   dt_atualizacao                  32 non-null     datetime64[ms, UTC]
 9   cd_usuario_atualizacao          32 non-null     object
 10  sg_subprefeitura                32 non-null     object
 11  qt_area_quilometro              32 non-null     int32
 12  qt_area_metro                   32 non-null     float64
 13  cd_regiao_05                    32 non-null     int32
 14  nm_regiao_05                    32 non-null     object
 15  cd_regiao_08                    32 non-null     int32
 16  nm_regiao_08                    32 non-null     object
 17  geometry_wkt                    32 non-null     object
dtypes: datetime64[ms, UTC](1), datetime64[ms](1), float64(1), int32(5), object(10)
memory usage: 4.0+ KB

### Removendo colunas específicas de `df_pandas_distrito`

Agora removeremos as colunas `tx_escala`, `sg_fonte_original`, `dt_criacao`, `dt_atualizacao`, `cd_usuario_atualizacao`, `cd_tipo_discrepancia`, `qt_area_quilometro`, `qt_area_metro`, `cd_regiao_05`, `nm_regiao_05`, `cd_regiao_08`, e `nm_regiao_08` do DataFrame `df_pandas_distrito` para simplificar o conjunto de dados conforme solicitado.

In [263]:
import pandas as pd

# Recria df_pandas_distrito para garantir que ele tenha todas as colunas originais de gdf_distrito
df_pandas_distrito = gdf_distrito.copy()
df_pandas_distrito['geometry_wkt'] = df_pandas_distrito['geometry'].apply(lambda geom: geom.wkt if geom else None)
df_pandas_distrito = df_pandas_distrito.drop(columns=['geometry'])

columns_to_drop_distrito = [
    'tx_escala',
    'sg_fonte_original',
    'dt_criacao',
    'dt_atualizacao',
    'cd_usuario_atualizacao',
    'cd_tipo_discrepancia',
    'qt_area_quilometro',
    'qt_area_metro',
    'cd_regiao_05',
    'nm_regiao_05',
    'cd_regiao_08',
    'nm_regiao_08'
]

# Remove as colunas de df_pandas_distrito
df_pandas_distrito = df_pandas_distrito.drop(columns=columns_to_drop_distrito)

print("Cabeçalho do DataFrame Pandas 'df_pandas_distrito' após remover colunas:")
display(df_pandas_distrito.head())

print("\nInformações do DataFrame Pandas 'df_pandas_distrito' após remover colunas:")
df_pandas_distrito.info()

Cabeçalho do DataFrame Pandas 'df_pandas_distrito' após remover colunas:

,id,cd_identificador_distrito,cd_identificador_subprefeitura,cd_distrito_municipal,nm_distrito_municipal,sg_distrito_municipal,geometry_wkt
0,distrito_municipal_v2.8583410,8583410,21,67,RIO PEQUENO,RPE,"POLYGON ((320567.4639 7394377.3124, 320581.183..."
1,distrito_municipal_v2.8583465,8583465,30,25,CIDADE TIRADENTES,CTI,"POLYGON ((357428.6884 7387653.528, 357433.4974..."
2,distrito_municipal_v2.8583484,8583484,24,46,JARDIM SAO LUIS,JDS,"POLYGON ((321618.4192 7377778.152, 321559.6291..."
3,distrito_municipal_v2.8583407,8583407,8,64,PONTE RASA,PRA,"POLYGON ((344730.8856 7398738.0871, 344738.505..."
4,distrito_municipal_v2.8583488,8583488,14,49,LIBERDADE,LIB,"POLYGON ((332504.5145 7392094.9838, 332505.951..."

Informações do DataFrame Pandas 'df_pandas_distrito' após remover colunas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              96 non-null     object
 1   cd_identificador_distrito       96 non-null     int32
 2   cd_identificador_subprefeitura  96 non-null     int32
 3   cd_distrito_municipal           96 non-null     object
 4   nm_distrito_municipal           96 non-null     object
 5   sg_distrito_municipal           96 non-null     object
 6   geometry_wkt                    96 non-null     object
dtypes: int32(2), object(5)
memory usage: 4.6+ KB

In [264]:
import re
from unidecode import unidecode # Certifique-se de que esta linha esteja presente ou remova se a importação já for global

columns_to_drop_subprefeitura = [
    'tx_escala',
    'sg_fonte_original',
    'dt_criacao',
    'cd_tipo_discrepancia',
    'dt_atualizacao',
    'cd_usuario_atualizacao',
    'sg_subprefeitura',
    'qt_area_quilometro',
    'qt_area_metro',
    'cd_regiao_05',
    'nm_regiao_05',
    'cd_regiao_08',
    'nm_regiao_08'
]

# Remove as colunas de df_pandas_subprefeitura
df_pandas_subprefeitura = df_pandas_subprefeitura.drop(columns=columns_to_drop_subprefeitura)

# Limpa a coluna 'nm_subprefeitura' para consistência
df_pandas_subprefeitura['nm_subprefeitura'] = df_pandas_subprefeitura['nm_subprefeitura'].str.upper()

# Usa a função unidecode e a normalização de traços
df_pandas_subprefeitura['nm_subprefeitura'] = df_pandas_subprefeitura['nm_subprefeitura'].apply(remove_accents_and_normalize)

print("Cabeçalho do DataFrame Pandas 'df_pandas_subprefeitura' após remover colunas e limpar 'nm_subprefeitura':")
display(df_pandas_subprefeitura.head())

print("\nInformações do DataFrame Pandas 'df_pandas_subprefeitura' após remover colunas e limpar 'nm_subprefeitura':")
df_pandas_subprefeitura.info()

Cabeçalho do DataFrame Pandas 'df_pandas_subprefeitura' após remover colunas e limpar 'nm_subprefeitura':

,id,cd_identificador_subprefeitura,cd_subprefeitura,nm_subprefeitura,geometry_wkt
0,subprefeitura_v2.26,26,16,CIDADE-ADEMAR,"POLYGON ((332383.8317 7381216.0788, 332408.531..."
1,subprefeitura_v2.24,24,18,M-BOI-MIRIM,"POLYGON ((316695.7231 7378199.4713, 316704.833..."
2,subprefeitura_v2.15,15,25,MOOCA,"POLYGON ((334126.1094 7396389.0681, 334125.831..."
3,subprefeitura_v2.19,19,13,IPIRANGA,"POLYGON ((335254.6122 7391150.3765, 335253.982..."
4,subprefeitura_v2.13,13,08,LAPA,"POLYGON ((321633.7288 7393535.3646, 321633.031..."

Informações do DataFrame Pandas 'df_pandas_subprefeitura' após remover colunas e limpar 'nm_subprefeitura':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              32 non-null     object
 1   cd_identificador_subprefeitura  32 non-null     int32
 2   cd_subprefeitura                32 non-null     object
 3   nm_subprefeitura                32 non-null     object
 4   geometry_wkt                    32 non-null     object
dtypes: int32(1), object(4)
memory usage: 1.3+ KB

In [265]:
df_distrito_subprefeitura = pd.merge(df_pandas_distrito,
                                     df_pandas_subprefeitura[['cd_identificador_subprefeitura', 'nm_subprefeitura']],
                                     on='cd_identificador_subprefeitura',
                                     how='left')

df_distrito_subprefeitura = df_distrito_subprefeitura[['nm_distrito_municipal', 'nm_subprefeitura']].drop_duplicates().reset_index(drop=True)

print("Distritos com suas respectivas subprefeituras:")
display(df_distrito_subprefeitura)

df_subprefeitura_distritos = df_distrito_subprefeitura.groupby('nm_subprefeitura')['nm_distrito_municipal'].apply(list).reset_index()
df_subprefeitura_distritos.rename(columns={'nm_distrito_municipal': 'distritos_associados'}, inplace=True)

print("Subprefeituras com seus distritos associados:")
display(df_subprefeitura_distritos)

Distritos com suas respectivas subprefeituras:

   nm_distrito_municipal           nm_subprefeitura
0            RIO PEQUENO                    BUTANTA
1      CIDADE TIRADENTES          CIDADE-TIRADENTES
2        JARDIM SAO LUIS                M-BOI-MIRIM
3             PONTE RASA         ERMELINO-MATARAZZO
4              LIBERDADE                         SE
..                   ...                        ...
91                  PARI                      MOOCA
92              MARSILAC                PARELHEIROS
93                    SE                         SE
94         VILA MEDEIROS  VILA-MARIA-VILA-GUILHERME
95              TUCURUVI           SANTANA-TUCURUVI

[96 rows x 2 columns]

Subprefeituras com seus distritos associados:

,nm_subprefeitura,distritos_associados
0,ARICANDUVA-FORMOSA-CARRAO,"[VILA FORMOSA, ARICANDUVA, CARRAO]"
1,BUTANTA,"[RIO PEQUENO, VILA SONIA, MORUMBI, BUTANTA, RA..."
2,CAMPO-LIMPO,"[CAPAO REDONDO, CAMPO LIMPO, VILA ANDRADE]"
3,CAPELA-DO-SOCORRO,"[CIDADE DUTRA, GRAJAU, SOCORRO]"
4,CASA-VERDE-LIMAO-CACHOEIRINHA,"[CACHOEIRINHA, LIMAO, CASA VERDE]"
5,CIDADE-ADEMAR,"[PEDREIRA, CIDADE ADEMAR]"
6,CIDADE-TIRADENTES,[CIDADE TIRADENTES]
7,ERMELINO-MATARAZZO,"[PONTE RASA, ERMELINO MATARAZZO]"
8,FREGUESIA-BRASILANDIA,"[FREGUESIA DO O, BRASILANDIA]"
9,GUAIANASES,"[LAJEADO, GUAIANASES]"
10,IPIRANGA,"[CURSINO, SACOMA, IPIRANGA]"
11,ITAIM-PAULISTA,"[ITAIM PAULISTA, VILA CURUCA]"
12,ITAQUERA,"[PARQUE DO CARMO, ITAQUERA, JOSE BONIFACIO, CI..."
13,JABAQUARA,[JABAQUARA]
14,JACANA-TREMEMBE,"[JACANA, TREMEMBE]"
15,LAPA,"[JAGUARA, PERDIZES, LAPA, JAGUARE, VILA LEOPOL..."
16,M-BOI-MIRIM,"[JARDIM SAO LUIS, JARDIM ANGELA]"
17,MOOCA,"[AGUA RASA, BELEM, TATUAPE, BRAS, MOOCA, PARI]"
18,PARELHEIROS,"[PARELHEIROS, MARSILAC]"
19,PENHA,"[CANGAIBA, PENHA, VILA MATILDE, ARTUR ALVIM]"
20,PERUS-ANHANGUERA,"[ANHANGUERA, PERUS]"
21,PINHEIROS,"[ALTO DE PINHEIROS, PINHEIROS, JARDIM PAULISTA..."
22,PIRITUBA-JARAGUA,"[SAO DOMINGOS, JARAGUA, PIRITUBA]"
23,SANTANA-TUCURUVI,"[MANDAQUI, SANTANA, TUCURUVI]"
24,SANTO-AMARO,"[CAMPO GRANDE, CAMPO BELO, SANTO AMARO]"
25,SAO-MATEUS,"[IGUATEMI, SAO RAFAEL, SAO MATEUS]"
26,SAO-MIGUEL,"[SAO MIGUEL, JARDIM HELENA, VILA JACUI]"
27,SAPOPEMBA,[SAPOPEMBA]
28,SE,"[LIBERDADE, CAMBUCI, REPUBLICA, CONSOLACAO, BE..."
29,VILA-MARIA-VILA-GUILHERME,"[VILA MARIA, VILA GUILHERME, VILA MEDEIROS]"
30,VILA-MARIANA,"[SAUDE, MOEMA, VILA MARIANA]"
31,VILA-PRUDENTE,"[VILA PRUDENTE, SAO LUCAS]"

In [267]:
def encontrar_distrito_pela_subprefeitura(subprefeitura_name):
    # O nome da subprefeitura já vem normalizado de df_alagamentos_cge

    found_districts = []

    # Itera por cada linha de df_subprefeitura_distritos
    for index, row in df_subprefeitura_distritos.iterrows():
        ref_subpref_name = row['nm_subprefeitura']
        distritos = row['distritos_associados']

        # Regra 1: Correspondência exata
        if ref_subpref_name == subprefeitura_name:
            found_districts.extend(distritos)
            # Se uma correspondência exata for encontrada, geralmente é a melhor, então retorna imediatamente
            return list(set(found_districts))

        # Regra 2: O nome de referência começa com o nome da subprefeitura consultada
        # (ex: 'SANTANA-TUCURUVI' começa com 'SANTANA')
        if subprefeitura_name and ref_subpref_name.startswith(subprefeitura_name):
            found_districts.extend(distritos)

        # Regra 3: O nome da subprefeitura consultada começa com o nome de referência
        # (ex: 'SAO-MIGUEL-PAULISTA' começa com 'SAO-MIGUEL')
        if ref_subpref_name and subprefeitura_name.startswith(ref_subpref_name):
            found_districts.extend(distritos)

    # Retorna distritos únicos encontrados por todas as regras
    return list(set(found_districts)) if found_districts else []

# --- Exemplos de uso da função (agora com nomes normalizados para teste) ---

# Exemplo 1: VILA MARIANA
subprefeitura_teste_1_input = 'VILA MARIANA'
subprefeitura_teste_1_normalized = remove_accents_and_normalize(subprefeitura_teste_1_input)
distritos_teste_1 = encontrar_distrito_pela_subprefeitura(subprefeitura_teste_1_normalized)

if distritos_teste_1:
    print(f"Distritos associados com '{subprefeitura_teste_1_input}' ({subprefeitura_teste_1_normalized}): {distritos_teste_1}")
else:
    print(f"Nenhum distrito encontrado para a subprefeitura '{subprefeitura_teste_1_input}' ({subprefeitura_teste_1_normalized}).")

# Exemplo 2: CIDADE TIRADENTES
subprefeitura_teste_2_input = 'CIDADE TIRADENTES'
subprefeitura_teste_2_normalized = remove_accents_and_normalize(subprefeitura_teste_2_input)
distritos_teste_2 = encontrar_distrito_pela_subprefeitura(subprefeitura_teste_2_normalized)

if distritos_teste_2:
    print(f"Distritos associados com '{subprefeitura_teste_2_input}' ({subprefeitura_teste_2_normalized}): {distritos_teste_2}")
else:
    print(f"Nenhum distrito encontrado para a subprefeitura '{subprefeitura_teste_2_input}' ({subprefeitura_teste_2_normalized}).")

# Exemplo 3: FREGUESIA-DO-O (com o mapeamento manual aplicado antes da busca)
subprefeitura_teste_3_input = 'FREGUESIA-DO-O'
# Simulando o mapeamento que ocorre em populate_distrito_column_from_subprefeitura
manual_mapping_for_test = {'FREGUESIA-DO-O': 'FREGUESIA-BRASILANDIA'}
subprefeitura_teste_3_normalized_for_lookup = manual_mapping_for_test.get(subprefeitura_teste_3_input, subprefeitura_teste_3_input)
distritos_teste_3 = encontrar_distrito_pela_subprefeitura(subprefeitura_teste_3_normalized_for_lookup)

if distritos_teste_3:
    print(f"Distritos associados com '{subprefeitura_teste_3_input}' (busca por '{subprefeitura_teste_3_normalized_for_lookup}'): {distritos_teste_3}")
else:
    print(f"Nenhum distrito encontrado para a subprefeitura '{subprefeitura_teste_3_input}' (busca por '{subprefeitura_teste_3_normalized_for_lookup}').")

Distritos associados com 'VILA MARIANA' (VILA-MARIANA): ['SAUDE', 'VILA MARIANA', 'MOEMA']
Distritos associados com 'CIDADE TIRADENTES' (CIDADE-TIRADENTES): ['CIDADE TIRADENTES']
Distritos associados com 'FREGUESIA-DO-O' (busca por 'FREGUESIA-BRASILANDIA'): ['BRASILANDIA', 'FREGUESIA DO O']

In [268]:
# This cell was merged into cell 'c7a1a22a' to fix the NameError.

In [269]:
def encontrar_distrito_pela_subprefeitura(subprefeitura_name):
    # o nome da subprefeitura já está normalizado de df_alagamentos_cge

    found_districts = []

    # Itera por cada linha de df_subprefeitura_distritos
    for index, row in df_subprefeitura_distritos.iterrows():
        ref_subpref_name = row['nm_subprefeitura']
        distritos = row['distritos_associados']

        # Regra 1: Correspondência exata
        if ref_subpref_name == subprefeitura_name:
            found_districts.extend(distritos)
            # Se uma correspondência exata for encontrada, geralmente é a melhor, então retorne imediatamente
            return list(set(found_districts))

        # Regra 2: Nome de referência começa com o nome da consulta
        # (ex: 'SANTANA-TUCURUVI' começa com 'SANTANA')
        if subprefeitura_name and ref_subpref_name.startswith(subprefeitura_name):
            found_districts.extend(distritos)

        # Regra 3: Nome da consulta começa com o nome de referência
        # (ex: 'SAO-MIGUEL-PAULISTA' começa com 'SAO-MIGUEL')
        if ref_subpref_name and subprefeitura_name.startswith(ref_subpref_name):
            found_districts.extend(distritos)

    # Retorna distritos únicos encontrados por todas as regras
    return list(set(found_districts)) if found_districts else []

# Exemplos de uso:
subprefeitura_test = 'VILA MARIANA'
distritos_encontrados = encontrar_distrito_pela_subprefeitura(subprefeitura_test)

if distritos_encontrados:
    print(f"Distritos associados com '{subprefeitura_test}': {distritos_encontrados}")
else:
    print(f"Nenhum distrito encontrado para a subprefeitura '{subprefeitura_test}'.")

subprefeitura_test_2 = 'CIDADE TIRADENTES'
distritos_encontrados_2 = encontrar_distrito_pela_subprefeitura(subprefeitura_test_2)

if distritos_encontrados_2:
    print(f"Distritos associados com '{subprefeitura_test_2}': {distritos_encontrados_2}")
else:
    print(f"Nenhum distrito encontrado para a subprefeitura '{subprefeitura_test_2}'.")

Nenhum distrito encontrado para a subprefeitura 'VILA MARIANA'.
Nenhum distrito encontrado para a subprefeitura 'CIDADE TIRADENTES'.

### Transformando `alagamentos_cge_sp.csv` em um DataFrame

In [270]:
import pandas as pd

# response = s3.get_object(
#     Bucket=bucket_name,
#     Key="alagamentos/alagamentos_cge_sp.csv"
# )

# df_alagamentos_cge = pd.read_csv(io.BytesIO(response["Body"].read()))

alagamentos_cge_file_path = '/content/alagamentos_cge_sp.csv'
df_alagamentos_cge = pd.read_csv(alagamentos_cge_file_path)

print("Cabeçalho do DataFrame 'df_alagamentos_cge':")
display(df_alagamentos_cge)

Cabeçalho do DataFrame 'df_alagamentos_cge':

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia
0,2025-03-28,Zona Leste,Itaim Paulista,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,ALTURA DO NUMERO 7557
1,2025-03-28,Zona Norte,Vila Maria/ Vila Guilherme,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,ALTURA DO N. 1661
2,2025-03-28,Zona Oeste,Pinheiros,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,TODA EXTENSAO
3,2025-03-28,Zona Sudeste,Ipiranga,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,ALTURA DO N. 52
4,2025-03-31,Zona Leste,Itaquera,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,ALT NUMERO 843
...,...,...,...,...,...,...,...,...,...
485,2026-03-19,Zona Leste,Mooca,Inativo Transitável,12:57,13:19,R PEDRO VICENTE,UNICO,AV CRUZEIRO DO SUL
486,2026-03-19,Zona Norte,Santana,Inativo Transitável,12:33,12:50,AV ZAKI NARCHI,AMBOS,R URUPIARA
487,2026-03-19,Zona Oeste,Lapa,Inativo Intransitável,12:33,14:25,PC PASCOAL MARTINS,UNICO,AV MARQ DE SAO VICENTE
488,2026-03-19,Zona Sul,Campo Limpo,Inativo Intransitável,14:30,14:53,"AV ELIS MAAS, 940",AMBOS,AV COMENDADOR SANT'ANNA
489,2026-03-26,Centro,Sé,Inativo Transitável,15:35,16:10,R BARRA DO TIBAGI,UNICO,ALTURA DO N. 544

### Limpeza da coluna 'referencia'

Vou remover todos os caracteres não numéricos da coluna 'referencia' em `df_alagamentos_cge`, deixando apenas os dígitos.

In [271]:
# Remove todos os caracteres não numéricos da coluna 'referencia'
df_alagamentos_cge['referencia'] = df_alagamentos_cge['referencia'].str.replace(r'[^0-9]', '', regex=True)

print("DataFrame 'df_alagamentos_cge' após limpeza da coluna 'referencia':")
display(df_alagamentos_cge)

DataFrame 'df_alagamentos_cge' após limpeza da coluna 'referencia':

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia
0,2025-03-28,Zona Leste,Itaim Paulista,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557
1,2025-03-28,Zona Norte,Vila Maria/ Vila Guilherme,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661
2,2025-03-28,Zona Oeste,Pinheiros,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,
3,2025-03-28,Zona Sudeste,Ipiranga,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52
4,2025-03-31,Zona Leste,Itaquera,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843
...,...,...,...,...,...,...,...,...,...
485,2026-03-19,Zona Leste,Mooca,Inativo Transitável,12:57,13:19,R PEDRO VICENTE,UNICO,
486,2026-03-19,Zona Norte,Santana,Inativo Transitável,12:33,12:50,AV ZAKI NARCHI,AMBOS,
487,2026-03-19,Zona Oeste,Lapa,Inativo Intransitável,12:33,14:25,PC PASCOAL MARTINS,UNICO,
488,2026-03-19,Zona Sul,Campo Limpo,Inativo Intransitável,14:30,14:53,"AV ELIS MAAS, 940",AMBOS,
489,2026-03-26,Centro,Sé,Inativo Transitável,15:35,16:10,R BARRA DO TIBAGI,UNICO,544

### Tratamento de valores não numéricos na coluna 'referencia'

Agora, vou substituir quaisquer valores vazios ou que não sejam apenas números na coluna 'referencia' por '000' e, em seguida, converter a coluna para um tipo numérico.

In [272]:
# Substitui strings vazias (resultado da remoção de caracteres não numéricos) por '000'
df_alagamentos_cge['referencia'] = df_alagamentos_cge['referencia'].replace('', '0')

# Converte a coluna 'referencia' para tipo numérico, transformando erros em NaN
df_alagamentos_cge['referencia'] = pd.to_numeric(df_alagamentos_cge['referencia'], errors='coerce')

# Opcional: Preencher NaNs, caso existam, com 0, se for o comportamento desejado para valores que não puderam ser convertidos a número
df_alagamentos_cge['referencia'] = df_alagamentos_cge['referencia'].fillna(0).astype(int)

print("DataFrame 'df_alagamentos_cge' após tratamento da coluna 'referencia':")
display(df_alagamentos_cge.head())
print("\nTipo de dados da coluna 'referencia':")
print(df_alagamentos_cge['referencia'].dtype)

DataFrame 'df_alagamentos_cge' após tratamento da coluna 'referencia':

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia
0,2025-03-28,Zona Leste,Itaim Paulista,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557
1,2025-03-28,Zona Norte,Vila Maria/ Vila Guilherme,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661
2,2025-03-28,Zona Oeste,Pinheiros,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0
3,2025-03-28,Zona Sudeste,Ipiranga,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52
4,2025-03-31,Zona Leste,Itaquera,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843

Tipo de dados da coluna 'referencia':
int64

In [273]:
import re
from unidecode import unidecode # Certifique-se de que esta linha esteja presente ou remova se a importação já for global

df_alagamentos_cge['subprefeitura'] = df_alagamentos_cge['subprefeitura'].str.upper()
# Usa a função unidecode e a normalização de traços
df_alagamentos_cge['subprefeitura'] = df_alagamentos_cge['subprefeitura'].apply(remove_accents_and_normalize)

print("DataFrame 'df_alagamentos_cge' após processar a coluna 'subprefeitura':")
display(df_alagamentos_cge)

DataFrame 'df_alagamentos_cge' após processar a coluna 'subprefeitura':

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia
0,2025-03-28,Zona Leste,ITAIM-PAULISTA,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557
1,2025-03-28,Zona Norte,VILA-MARIA-VILA-GUILHERME,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661
2,2025-03-28,Zona Oeste,PINHEIROS,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0
3,2025-03-28,Zona Sudeste,IPIRANGA,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52
4,2025-03-31,Zona Leste,ITAQUERA,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843
...,...,...,...,...,...,...,...,...,...
485,2026-03-19,Zona Leste,MOOCA,Inativo Transitável,12:57,13:19,R PEDRO VICENTE,UNICO,0
486,2026-03-19,Zona Norte,SANTANA,Inativo Transitável,12:33,12:50,AV ZAKI NARCHI,AMBOS,0
487,2026-03-19,Zona Oeste,LAPA,Inativo Intransitável,12:33,14:25,PC PASCOAL MARTINS,UNICO,0
488,2026-03-19,Zona Sul,CAMPO-LIMPO,Inativo Intransitável,14:30,14:53,"AV ELIS MAAS, 940",AMBOS,0
489,2026-03-26,Centro,SE,Inativo Transitável,15:35,16:10,R BARRA DO TIBAGI,UNICO,544

In [274]:
# Adiciona uma nova coluna 'distrito' ao DataFrame, inicializada como vazia
df_alagamentos_cge['distrito'] = ''

print("DataFrame 'df_alagamentos_cge' com a nova coluna 'distrito' vazia:")
display(df_alagamentos_cge.head())

DataFrame 'df_alagamentos_cge' com a nova coluna 'distrito' vazia:

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia,distrito
0,2025-03-28,Zona Leste,ITAIM-PAULISTA,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557,
1,2025-03-28,Zona Norte,VILA-MARIA-VILA-GUILHERME,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661,
2,2025-03-28,Zona Oeste,PINHEIROS,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0,
3,2025-03-28,Zona Sudeste,IPIRANGA,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52,
4,2025-03-31,Zona Leste,ITAQUERA,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843,

In [275]:
def populate_distrito_column_from_subprefeitura(row):
    subprefeitura_name = row['subprefeitura']

    # --- Mapeado manualmente pois
    # --- ARICANDUVA-VILA-FORMOSA (do df_alagamentos_cge) e FREGUESIA-DO-O (do df_alagamentos_cge)
    # --- vs. ARICANDUVA-FORMOSA-CARRAO (do df_subprefeitura_distritos) FREGUESIA-O (do df_subprefeitura_distritos)--- Correção manual de 'FREGUESIA-O' para 'FREGUESIA-BRASILANDIA'
    manual_mapping = {
        'ARICANDUVA-VILA-FORMOSA': 'ARICANDUVA-FORMOSA-CARRAO',
        'FREGUESIA-DO-O': 'FREGUESIA-BRASILANDIA'
    }
    # Aplica o mapeamento se o nome da subprefeitura estiver no mapa
    subprefeitura_name_for_lookup = manual_mapping.get(subprefeitura_name, subprefeitura_name)

    distritos_found = encontrar_distrito_pela_subprefeitura(subprefeitura_name_for_lookup)

    if distritos_found:

        return ', '.join(distritos_found)
    else:
        return None

# Aplica a função ao DataFrame df_alagamentos_cge
df_alagamentos_cge['distrito'] = df_alagamentos_cge.apply(populate_distrito_column_from_subprefeitura, axis=1)

print("DataFrame 'df_alagamentos_cge' após preencher a coluna 'distrito':")
display(df_alagamentos_cge.head())

DataFrame 'df_alagamentos_cge' após preencher a coluna 'distrito':

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia,distrito
0,2025-03-28,Zona Leste,ITAIM-PAULISTA,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557,"VILA CURUCA, ITAIM PAULISTA"
1,2025-03-28,Zona Norte,VILA-MARIA-VILA-GUILHERME,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661,"VILA MARIA, VILA MEDEIROS, VILA GUILHERME"
2,2025-03-28,Zona Oeste,PINHEIROS,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0,"ALTO DE PINHEIROS, JARDIM PAULISTA, ITAIM BIBI..."
3,2025-03-28,Zona Sudeste,IPIRANGA,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52,"CURSINO, IPIRANGA, SACOMA"
4,2025-03-31,Zona Leste,ITAQUERA,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843,"CIDADE LIDER, ITAQUERA, PARQUE DO CARMO, JOSE ..."

In [276]:
print("Contagem de valores nulos por coluna em 'df_alagamentos_cge':")
display(df_alagamentos_cge.isnull().sum())

Contagem de valores nulos por coluna em 'df_alagamentos_cge':

data             0
zona             0
subprefeitura    0
status           0
hora_inicio      0
hora_fim         0
logradouro       0
sentido          0
referencia       0
distrito         0
dtype: int64

In [277]:
print("Informações sobre as colunas e seus tipos de dados em 'df_alagamentos_cge':")
df_alagamentos_cge.info()

Informações sobre as colunas e seus tipos de dados em 'df_alagamentos_cge':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data           490 non-null    object
 1   zona           490 non-null    object
 2   subprefeitura  490 non-null    object
 3   status         490 non-null    object
 4   hora_inicio    490 non-null    object
 5   hora_fim       490 non-null    object
 6   logradouro     490 non-null    object
 7   sentido        490 non-null    object
 8   referencia     490 non-null    int64
 9   distrito       490 non-null    object
dtypes: int64(1), object(9)
memory usage: 38.4+ KB

In [278]:
# Normaliza a coluna 'logradouro' usando a função remove_accents_and_normalize, mantendo os espaços
df_alagamentos_cge['logradouro'] = df_alagamentos_cge['logradouro'].apply(lambda x: remove_accents_and_normalize(x, keep_spaces=True))

print("DataFrame 'df_alagamentos_cge' após normalizar a coluna 'logradouro' (mantendo espaços):")
display(df_alagamentos_cge.head())

DataFrame 'df_alagamentos_cge' após normalizar a coluna 'logradouro' (mantendo espaços):

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia,distrito
0,2025-03-28,Zona Leste,ITAIM-PAULISTA,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557,"VILA CURUCA, ITAIM PAULISTA"
1,2025-03-28,Zona Norte,VILA-MARIA-VILA-GUILHERME,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661,"VILA MARIA, VILA MEDEIROS, VILA GUILHERME"
2,2025-03-28,Zona Oeste,PINHEIROS,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0,"ALTO DE PINHEIROS, JARDIM PAULISTA, ITAIM BIBI..."
3,2025-03-28,Zona Sudeste,IPIRANGA,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52,"CURSINO, IPIRANGA, SACOMA"
4,2025-03-31,Zona Leste,ITAQUERA,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843,"CIDADE LIDER, ITAQUERA, PARQUE DO CARMO, JOSE ..."

Colocar coluna de latitude e longitude -

Depois filtrar para ter apenas 1 dos distritos, caso na coluna distrito tenha mais de 1 distrito -

depois tratar as outras colunas que já estavam no CGE
Exemplo_2: coluna data e coluna hora, formatar para virar uma coluna só datetime.

In [279]:
# Instala a biblioteca geopy para geocodificação, se ainda não estiver instalada
!pip install geopy

Requirement already satisfied: geopy in /usr/local/lib/python3.12/dist-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.12/dist-packages (from geopy) (2.1)

In [280]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import numpy as np

# Inicializa o geocodificador Nominatim com um timeout maior
geolocator = Nominatim(user_agent="geo_flooding_analysis", timeout=1)

# Adiciona um limitador de taxa para evitar bloqueios da API (1 requisição por segundo)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

print("Geocodificador Nominatim configurado com timeout de 1 segundos.")

Geocodificador Nominatim configurado com timeout de 2 segundos.

### Refinando a Coluna 'distrito' com Geocodificação

In [281]:
def populate_distrito_column_from_subprefeitura_refined(row):
    subprefeitura_name = row['subprefeitura']
    logradouro = row['logradouro']

    manual_mapping = {
        'ARICANDUVA-VILA-FORMOSA': 'ARICANDUVA-FORMOSA-CARRAO',
        'FREGUESIA-DO-O': 'FREGUESIA-BRASILANDIA'
    }
    subprefeitura_name_for_lookup = manual_mapping.get(subprefeitura_name, subprefeitura_name)

    distritos_found = encontrar_distrito_pela_subprefeitura(subprefeitura_name_for_lookup)

    if not distritos_found:
        # print(f"Nenhum distrito encontrado para subprefeitura '{subprefeitura_name}'")
        return None # Nenhum distrito encontrado para a subprefeitura

    if len(distritos_found) == 1:
        # print(f"Distrito único encontrado para '{subprefeitura_name}': {distritos_found[0]}")
        return distritos_found[0] # Se apenas um distrito, usa-o diretamente

    # Se múltiplos distritos, tenta refinar usando o logradouro
    best_distrito = None
    best_match_score = -1 # Score mais alto indica melhor correspondência

    for distrito_name in distritos_found:
        # Cria uma query para o logradouro e distrito específicos
        query = f"{logradouro}, {distrito_name}, São Paulo, Brazil"
        try:
            location = geocode(query)

            if location:
                # Verifica se o logradouro e o distrito fazem parte do endereço geocodificado
                address_lower = location.address.lower()
                logradouro_lower = logradouro.lower()
                distrito_lower = distrito_name.lower()

                current_score = 0
                if logradouro_lower in address_lower:
                    current_score += 1
                if distrito_lower in address_lower: # Dá maior preferência se o distrito estiver claro no endereço
                    current_score += 2

                if current_score > best_match_score:
                    best_match_score = current_score
                    best_distrito = distrito_name

        except Exception as e:
            # print(f"Erro ao geocodificar '{query}' para refinamento: {e}")
            pass # Ignora erros nas tentativas de refinamento

    if best_distrito:
        print(f"Refinado para '{best_distrito}' para logradouro '{logradouro}' na subprefeitura '{subprefeitura_name}'")
        return best_distrito
    elif distritos_found:
        print(f"Não foi possível refinar para um distrito único, usando o primeiro: '{distritos_found[0]}' para '{logradouro}' na subprefeitura '{subprefeitura_name}'")
        # Se nenhuma correspondência específica por geocodificação foi forte, retorna o primeiro distrito como fallback
        return distritos_found[0]
    else:
        # print(f"Nenhum distrito final determinado para '{logradouro}' na subprefeitura '{subprefeitura_name}'")
        return None # Não deve acontecer se distritos_found não estiver vazio

# Aplica a função refinada ao DataFrame df_alagamentos_cge
df_alagamentos_cge['distrito'] = df_alagamentos_cge.apply(populate_distrito_column_from_subprefeitura_refined, axis=1)

print("DataFrame 'df_alagamentos_cge' após preencher e refinar a coluna 'distrito':")
display(df_alagamentos_cge.head())

Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'VILA MEDEIROS' para logradouro 'AV JULIO BUONO' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Não foi possível refinar para um distrito único, usando o primeiro: 'ALTO DE PINHEIROS' para 'R BRIG HAROLDO VELOSO' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'R MAEST EDMUNDO PERUZZI' na subprefeitura 'IPIRANGA'
Refinado para 'CIDADE LIDER' para logradouro 'AV OSVALDO VALLE CORDEIRO' na subprefeitura 'ITAQUERA'
Não foi possível refinar para um distrito único, usando o primeiro: 'AGUA RASA' para 'R PROFESSORA SEBASTIANA SILVA MINHOTO' na subprefeitura 'MOOCA'
Refinado para 'VILA PRUDENTE' para logradouro 'AV PROF LUIZ IGNACIO ANHAIA MELLO' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'MORUMBI' para logradouro 'AV PROF FRANCISCO MORATO' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'ALTO DE PINHEIROS' para 'R BRIG HAROLDO VELOSO' na subprefeitura 'PINHEIROS'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AV DRA RUTH CARDOSO' na subprefeitura 'PINHEIROS'
Refinado para 'IPIRANGA' para logradouro 'ESTRADA DAS LAGRIMAS' na subprefeitura 'IPIRANGA'
Refinado para 'IPIRANGA' para logradouro 'AV ALM DELAMARE' na subprefeitura 'IPIRANGA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'ES DAS LAGRIMAS' na subprefeitura 'IPIRANGA'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AL SANTOS' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Refinado para 'BOM RETIRO' para logradouro 'AV DO ESTADO' na subprefeitura 'SE'
Refinado para 'BELA VISTA' para logradouro 'R DA CONSOLACAO' na subprefeitura 'SE'
Refinado para 'BELA VISTA' para logradouro 'AL DINO BUENO' na subprefeitura 'SE'
Refinado para 'JACANA' para logradouro 'AV PAULO LINCOLN DO VALLE PONTIN' na subprefeitura 'JACANA-TREMEMBE'
Refinado para 'JACANA' para logradouro 'AV ANTONELO DA MESSINA' na subprefeitura 'JACANA-TREMEMBE'
Não foi possível refinar para um distrito único, usando o primeiro: 'SANTANA' para 'PTE DAS BANDEIRAS SEN ROMEU TUMA' na subprefeitura 'SANTANA'
Refinado para 'SANTANA' para logradouro 'R CEL ANTONIO DE CARVALHO' na subprefeitura 'SANTANA'
Refinado para 'BOM RETIRO' para logradouro 'AV RIO BRANCO' na subprefeitura 'SE'
Refinado para 'VILA FORMOSA' para logradouro 'AV REG FEIJO' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'ITAQUERA' para logradouro 'AV ITAQUERA' na subprefeitura 'ITAQUERA'
Refinado para 'CIDADE LIDER' para logradouro 'AV OSVALDO VALLE CORDEIRO' na subprefeitura 'ITAQUERA'
Refinado para 'RAPOSO TAVARES' para logradouro 'AV VITAL BRASIL' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARDIM ANGELA' para 'ES M BOI MIRIM' na subprefeitura 'M-BOI-MIRIM'
Refinado para 'BELA VISTA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'R DR RODRIGO DE BARROS' na subprefeitura 'SE'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=PC+DA+REPUBLICA%2C+BOM+RETIRO%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=PC+DA+REPUBLICA%2C+BELA+VISTA%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Refinado para 'SE' para logradouro 'PC DA REPUBLICA' na subprefeitura 'SE'
Refinado para 'GUAIANASES' para logradouro 'RUA ALEXANDRE LEGRAND' na subprefeitura 'GUAIANASES'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'CASA VERDE' para logradouro 'AV ORDEM E PROGRESSO' na subprefeitura 'CASA-VERDE'
Refinado para 'CASA VERDE' para logradouro 'AV ORDEM E PROGRESSO' na subprefeitura 'CASA-VERDE'
Refinado para 'SANTANA' para logradouro 'MARGINAL TIETE ASCB CENTRAL' na subprefeitura 'SANTANA'
Refinado para 'BARRA FUNDA' para logradouro 'PC PASCOAL MARTINS' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'PTE DO PIQUERI JOELMIR BETING' na subprefeitura 'LAPA'
Refinado para 'IGUATEMI' para logradouro 'AV ARICANDUVA' na subprefeitura 'SAO-MATEUS'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'AV CD DE FRONTIN' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'VD GAL OLIMPIO DA SILVEIRA' na subprefeitura 'LAPA'
Refinado para 'BRAS' para logradouro 'AV CELSO GARCIA' na subprefeitura 'MOOCA'
Refinado para 'BOM RETIRO' para logradouro 'AV S JOAO' na subprefeitura 'SE'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAQUERA' para logradouro 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'ITAQUERA'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AV PEDROSO DE MORAIS' na subprefeitura 'PINHEIROS'
Refinado para 'ARTUR ALVIM' para logradouro 'R DR LUIZ AYRES' na subprefeitura 'PENHA'
Refinado para 'CASA VERDE' para logradouro 'R REIMS' na subprefeitura 'CASA-VERDE'
Refinado para 'MORUMBI' para logradouro 'AV ALCIDES SANGIRARDI' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV ALCIDES SANGIRARDI' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SE' para 'VEL PRES JOAO GOULART' na subprefeitura 'SE'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=VD+ENG+ALBERTO+BADRA%2C+ARICANDUVA%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Não foi possível refinar para um distrito único, usando o primeiro: 'ARICANDUVA' para 'VD ENG ALBERTO BADRA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'SANTANA' para logradouro 'R DR GABRIEL PIZA' na subprefeitura 'SANTANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'AV MARQ DE SAO VICENTE' na subprefeitura 'LAPA'
Refinado para 'BOM RETIRO' para logradouro 'AV DO ESTADO' na subprefeitura 'SE'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AV PEDROSO DE MORAIS' na subprefeitura 'PINHEIROS'
Refinado para 'SANTANA' para logradouro 'AV GAL ATALIBA LEONEL' na subprefeitura 'SANTANA'
Refinado para 'SE' para logradouro 'R NORMA PIERUCCINI GIANNOTTI' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AL NOTHMANN' na subprefeitura 'SE'
Não foi possível refinar para um distrito único, usando o primeiro: 'SE' para 'R PRES BATISTA PEREIRA' na subprefeitura 'SE'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Refinado para 'SAO MATEUS' para logradouro 'PC FELISBERTO FERNANDES DA SILVA' na subprefeitura 'SAO-MATEUS'
Refinado para 'PIRITUBA' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'PIRITUBA-JARAGUA'
Refinado para 'PIRITUBA' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'PIRITUBA-JARAGUA'
Refinado para 'BARRA FUNDA' para logradouro 'PC PASCOAL MARTINS' na subprefeitura 'LAPA'
Refinado para 'ITAIM BIBI' para logradouro 'AV DOS BANDEIRANTES' na subprefeitura 'PINHEIROS'
Refinado para 'JARDIM PAULISTA' para logradouro 'R HENRIQUE SCHAUMANN' na subprefeitura 'PINHEIROS'
Refinado para 'PINHEIROS' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'PINHEIROS'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AV PEDROSO DE MORAIS' na subprefeitura 'PINHEIROS'
Refinado para 'IPIRANGA' para logradouro 'R DOS PATRIOTAS' na subprefeitura 'IPIRANGA'
Refinado para 'SAUDE' para logradouro 'AV PROF ABRAAO DE MORAIS' na subprefeitura 'VILA-MARIANA'
Refinado para 'VILA MARIANA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'VILA-MARIANA'
Refinado para 'SAUDE' para logradouro 'PC LEONOR KAUPA' na subprefeitura 'VILA-MARIANA'
Refinado para 'SAUDE' para logradouro 'AV PROF ABRAAO DE MORAIS' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO LIMPO' para logradouro 'R ALVES DOS SANTOS' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'SOCORRO' para logradouro 'AV GUARAPIRANGA' na subprefeitura 'CAPELA-DO-SOCORRO'
Refinado para 'SOCORRO' para logradouro 'AV GUARAPIRANGA' na subprefeitura 'CAPELA-DO-SOCORRO'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARDIM ANGELA' para 'ES M BOI MIRIM' na subprefeitura 'M-BOI-MIRIM'
Refinado para 'CAMPO GRANDE' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'SANTO-AMARO'
Refinado para 'SANTO AMARO' para logradouro 'AV ROQUE PETRONI JUNIOR' na subprefeitura 'SANTO-AMARO'
Refinado para 'VILA LEOPOLDINA' para logradouro 'AV QUEIROZ FILHO' na subprefeitura 'LAPA'
Refinado para 'SE' para logradouro 'R PAULA SOUSA' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV DO ESTADO' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV DO ESTADO' na subprefeitura 'SE'
Refinado para 'ARICANDUVA' para logradouro 'AV ARICANDUVA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'AGUA RASA' para logradouro 'AV SALIM FARAH MALUF' na subprefeitura 'MOOCA'
Refinado para 'FREGUESIA DO O' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'FREGUESIA-DO-O'
Refinado para 'FREGUESIA DO O' para logradouro 'MARGINAL TIETE' na subprefeitura 'FREGUESIA-DO-O'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARAGUA' para 'MARGINAL TIETE ASCB EXPRESSA' na subprefeitura 'PIRITUBA-JARAGUA'
Refinado para 'BARRA FUNDA' para logradouro 'PC PASCOAL MARTINS' na subprefeitura 'LAPA'
Refinado para 'VILA MARIANA' para logradouro 'AV DR RICARDO JAFET' na subprefeitura 'VILA-MARIANA'
Refinado para 'MOEMA' para logradouro 'AV PEDRO ALVARES CABRAL' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO GRANDE' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'SANTO-AMARO'
Refinado para 'CAMPO GRANDE' para logradouro 'AV SANTO AMARO' na subprefeitura 'SANTO-AMARO'
Refinado para 'FREGUESIA DO O' para logradouro 'MARGINAL TIETE' na subprefeitura 'FREGUESIA-DO-O'
Refinado para 'BARRA FUNDA' para logradouro 'PC PASCOAL MARTINS' na subprefeitura 'LAPA'
Refinado para 'BARRA FUNDA' para logradouro 'PC LUIZ CARLOS MESQUITA' na subprefeitura 'LAPA'
Refinado para 'BARRA FUNDA' para logradouro 'AV MARIO DE ANDRADE' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SE' para 'VEL PRES JOAO GOULART' na subprefeitura 'SE'
Refinado para 'SE' para logradouro 'R PAULA SOUSA' na subprefeitura 'SE'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=R+DOM+RODO%2C+REPUBLICA%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Refinado para 'BOM RETIRO' para logradouro 'R DOM RODO' na subprefeitura 'SE'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'VD ENG ALBERTO BADRA' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Refinado para 'FREGUESIA DO O' para logradouro 'MARGINAL TIETE' na subprefeitura 'FREGUESIA-DO-O'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'VEL PRES JOAO GOULART' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'AV COMEN MARTINELLI' na subprefeitura 'LAPA'
Refinado para 'VILA MARIANA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'VILA-MARIANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARDIM ANGELA' para 'ES DE ITAPECERICA' na subprefeitura 'M-BOI-MIRIM'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARDIM ANGELA' para 'ES M BOI MIRIM' na subprefeitura 'M-BOI-MIRIM'
Refinado para 'CAMPO GRANDE' para logradouro 'AV SANTO AMARO' na subprefeitura 'SANTO-AMARO'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'SANTANA' para logradouro 'AV GAL ATALIBA LEONEL' na subprefeitura 'SANTANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CIDADE ADEMAR' para 'PC TUNEY ARANTES' na subprefeitura 'CIDADE-ADEMAR'
Refinado para 'BARRA FUNDA' para logradouro 'R ZIMON LEIRNER' na subprefeitura 'LAPA'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AL SANTOS' na subprefeitura 'PINHEIROS'
Refinado para 'ITAQUERA' para logradouro 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'ITAQUERA'
Refinado para 'MORUMBI' para logradouro 'AV MAGALHAES DE CASTRO' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV ALCIDES SANGIRARDI' na subprefeitura 'BUTANTA'
Refinado para 'PINHEIROS' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'PINHEIROS'
Refinado para 'CAMPO GRANDE' para logradouro 'AV STO AMARO' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Não foi possível refinar para um distrito único, usando o primeiro: 'PARELHEIROS' para 'ES ECOTURISTICA DE PARELHEIROS' na subprefeitura 'PARELHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'PARELHEIROS' para 'ES ECOTURISTICA DE PARELHEIROS' na subprefeitura 'PARELHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'AV CD DE FRONTIN' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'VILA MARIA' para 'PTE PRES JANIO QUADROS' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'MORUMBI' para logradouro 'AV PROF FRANCISCO MORATO' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'TN PRES JANIO QUADROS' na subprefeitura 'BUTANTA'
Refinado para 'ITAIM BIBI' para logradouro 'TN MAX FEFFER' na subprefeitura 'PINHEIROS'
Refinado para 'ITAIM BIBI' para logradouro 'MARGINAL PINHEIROS INTCB' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'ALTO DE PINHEIROS' para 'PTE OCTAVIO FRIAS DE OLIVEIRA' na subprefeitura 'PINHEIROS'
Refinado para 'ITAIM BIBI' para logradouro 'MARGINAL PINHEIROS INTCB' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'VD GRANDE SAO PAULO VER M O SALA' na subprefeitura 'IPIRANGA'
Refinado para 'MOEMA' para logradouro 'PC JUCA MULATO' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO GRANDE' para logradouro 'AL STO AMARO' na subprefeitura 'SANTO-AMARO'
Refinado para 'ARICANDUVA' para logradouro 'AV ARICANDUVA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'FREGUESIA DO O' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'FREGUESIA-DO-O'
Refinado para 'VILA MARIANA' para logradouro 'AV IBIRAPUERA' na subprefeitura 'VILA-MARIANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SE' para 'PTE DAS BANDEIRAS SEN ROMEU TUMA' na subprefeitura 'SE'
Refinado para 'IGUATEMI' para logradouro 'AV ARICANDUVA' na subprefeitura 'SAO-MATEUS'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Não foi possível refinar para um distrito único, usando o primeiro: 'SAUDE' para 'CV JOAO JORGE SAAD' na subprefeitura 'VILA-MARIANA'
Refinado para 'ITAQUERA' para logradouro 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'ITAQUERA'
Refinado para 'BOM RETIRO' para logradouro 'AV RIO BRANCO' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV RIO BRANCO' na subprefeitura 'SE'
Refinado para 'ITAQUERA' para logradouro 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'ITAQUERA'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Refinado para 'MORUMBI' para logradouro 'AV MAGALHAES DE CASTRO' na subprefeitura 'BUTANTA'
Refinado para 'CASA VERDE' para logradouro 'R REIMS' na subprefeitura 'CASA-VERDE'
Refinado para 'VILA GUILHERME' para logradouro 'R MIGUEL MENTEM' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'BELA VISTA' para logradouro 'TN S JOAO PAULO II' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'R CRUZEIRO' na subprefeitura 'SE'
Refinado para 'SE' para logradouro 'R NORMA PIERUCCINI GIANNOTTI' na subprefeitura 'SE'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=R+ANHANGUERA%2C+SE%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Refinado para 'SE' para logradouro 'R ANHANGUERA' na subprefeitura 'SE'
Refinado para 'SE' para logradouro 'R ANHANGUERA' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV RIO BRANCO' na subprefeitura 'SE'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'RUA MANUEL BARBALHO DE LIMA' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'PARI' para logradouro 'AV CRUZEIRO DO SUL' na subprefeitura 'MOOCA'
Refinado para 'MORUMBI' para logradouro 'AV ALCIDES SANGIRARDI' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SAUDE' para 'CV TRIBUNAL DE JUSTICA DO E SP' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO GRANDE' para logradouro 'AV STO AMARO' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'BRASILANDIA' para 'R MANOEL BARBOSA' na subprefeitura 'FREGUESIA-DO-O'
Refinado para 'PIRITUBA' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'PIRITUBA-JARAGUA'
Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV PDE LEBRET' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV PROF FRANCISCO MORATO' na subprefeitura 'BUTANTA'
Refinado para 'RAPOSO TAVARES' para logradouro 'R DOS PIEMONTESES' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'R PRES BATISTA PEREIRA' na subprefeitura 'IPIRANGA'
Refinado para 'LIMAO' para logradouro 'AV ANTONIO MUNHOZ BONILHA' na subprefeitura 'CASA-VERDE'
Refinado para 'PIRITUBA' para logradouro 'MARGINAL TIETE' na subprefeitura 'PIRITUBA-JARAGUA'
Refinado para 'MORUMBI' para logradouro 'AV PROF FRANCISCO MORATO' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'ALTO DE PINHEIROS' para 'PC PAN-AMERICANA' na subprefeitura 'PINHEIROS'
Refinado para 'SE' para logradouro 'AV MERCURIO' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'R DOM RODO' na subprefeitura 'SE'
Não foi possível refinar para um distrito único, usando o primeiro: 'AGUA RASA' para 'VD GUADALAJARA-JOAO BEHISNELIAN' na subprefeitura 'MOOCA'
Refinado para 'PIRITUBA' para logradouro 'MARGINAL TIETE' na subprefeitura 'PIRITUBA-JARAGUA'
Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV ENG BILLINGS' na subprefeitura 'BUTANTA'
Refinado para 'BARRA FUNDA' para logradouro 'AV PRES CASTELO BRANCO' na subprefeitura 'LAPA'
Refinado para 'PINHEIROS' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'PINHEIROS'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'MARGINAL PINHEIROS' na subprefeitura 'PINHEIROS'
Refinado para 'SE' para logradouro 'R DA FIGUEIRA' na subprefeitura 'SE'
Refinado para 'JARDIM ANGELA' para logradouro 'AV GUARAPIRANGA' na subprefeitura 'M-BOI-MIRIM'
Refinado para 'SE' para logradouro 'AV MERCURIO' na subprefeitura 'SE'
Refinado para 'SE' para logradouro 'AV PRES CASTELO BRANCO' na subprefeitura 'SE'
Refinado para 'SE' para logradouro 'MARGINAL TIETE CBAS EXPRESSA' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV SANTOS DUMONT' na subprefeitura 'SE'
Refinado para 'ARICANDUVA' para logradouro 'AV ARICANDUVA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'CARRAO' para logradouro 'R CARLOS SILVA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'ARICANDUVA' para logradouro 'AV ARICANDUVA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'ARICANDUVA' para logradouro 'AV ARICANDUVA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'MOOCA' para logradouro 'R HIPODROMO' na subprefeitura 'MOOCA'
Refinado para 'MOOCA' para logradouro 'AV ALCANTARA MACHADO' na subprefeitura 'MOOCA'
Refinado para 'PARI' para logradouro 'AV CRUZEIRO DO SUL' na subprefeitura 'MOOCA'
Refinado para 'BELEM' para logradouro 'AV PRES CASTELO BRANCO' na subprefeitura 'MOOCA'
Refinado para 'PENHA' para logradouro 'AV AIRTON PRETINI' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'AV CD DE FRONTIN' na subprefeitura 'PENHA'
Refinado para 'IGUATEMI' para logradouro 'AV ARICANDUVA' na subprefeitura 'SAO-MATEUS'
Refinado para 'FREGUESIA DO O' para logradouro 'R BONIFACIO CUBAS' na subprefeitura 'FREGUESIA-DO-O'
Refinado para 'FREGUESIA DO O' para logradouro 'AV STA MARINA' na subprefeitura 'FREGUESIA-DO-O'
Refinado para 'PIRITUBA' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'PIRITUBA-JARAGUA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SANTANA' para 'PTE DAS BANDEIRAS SEN ROMEU TUMA' na subprefeitura 'SANTANA'
Refinado para 'SANTANA' para logradouro 'AV CRUZEIRO DO SUL' na subprefeitura 'SANTANA'
Refinado para 'SANTANA' para logradouro 'MARGINAL TIETE' na subprefeitura 'SANTANA'
Refinado para 'SANTANA' para logradouro 'MARGINAL TIETE' na subprefeitura 'SANTANA'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=R+CHICO+PONTES%2C+VILA+MARIA%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Refinado para 'VILA MARIA' para logradouro 'R CHICO PONTES' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'BARRA FUNDA' para logradouro 'AV EMB MACEDO SOARES' na subprefeitura 'LAPA'
Refinado para 'BOM RETIRO' para logradouro 'AV RUDGE' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV SANTOS DUMONT' na subprefeitura 'SE'
Refinado para 'VILA FORMOSA' para logradouro 'AV DR EDUARDO COTCHING' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'VILA FORMOSA' para logradouro 'AV DR EDUARDO COTCHING' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'GUAIANASES' para logradouro 'RUA ALEXANDRE LEGRAND' na subprefeitura 'GUAIANASES'
Refinado para 'GUAIANASES' para logradouro 'RUA ANDREAS RASELIUS' na subprefeitura 'GUAIANASES'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CIDADE LIDER' para 'VD LADEIRA DO XISTO' na subprefeitura 'ITAQUERA'
Refinado para 'ITAQUERA' para logradouro 'AV ITAQUERA' na subprefeitura 'ITAQUERA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CIDADE LIDER' para 'R PDE VIEGAS DE MENEZES' na subprefeitura 'ITAQUERA'
Refinado para 'ITAQUERA' para logradouro 'AV JOSE PINHEIRO BORGES' na subprefeitura 'ITAQUERA'
Refinado para 'ITAQUERA' para logradouro 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'ITAQUERA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'AV CD DE FRONTIN' na subprefeitura 'PENHA'
Refinado para 'SANTANA' para logradouro 'AV CRUZEIRO DO SUL' na subprefeitura 'SANTANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SANTANA' para 'PTE DAS BANDEIRAS SEN ROMEU TUMA' na subprefeitura 'SANTANA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'PINHEIROS' para logradouro 'R HUNGRIA' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'AV PRES TANCREDO NEVES' na subprefeitura 'IPIRANGA'
Refinado para 'SAUDE' para logradouro 'R GAL CHAGAS SANTOS' na subprefeitura 'VILA-MARIANA'
Refinado para 'SAUDE' para logradouro 'AV PROF ABRAAO DE MORAIS' na subprefeitura 'VILA-MARIANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SAUDE' para '16-PC JUCA MULATO X AV ASCENDINO REIS C B AV PROF ASCENDINO REIS' na subprefeitura 'VILA-MARIANA'
Refinado para 'VILA MARIANA' para logradouro 'AV IBIRAPUERA' na subprefeitura 'VILA-MARIANA'
Refinado para 'VILA MARIANA' para logradouro 'AV IBIRAPUERA' na subprefeitura 'VILA-MARIANA'
Refinado para 'MOEMA' para logradouro 'AV MOREIRA GUIMARAES' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO GRANDE' para logradouro 'AV SANTO AMARO' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARAGUA' para 'PSS FANDI CHAQUIB KALIL' na subprefeitura 'PIRITUBA-JARAGUA'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARAGUA' para 'MARGINAL TIETE ASCB EXPRESSA' na subprefeitura 'PIRITUBA-JARAGUA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'VILA LEOPOLDINA' para logradouro 'PC APECATU' na subprefeitura 'LAPA'
Refinado para 'VILA LEOPOLDINA' para logradouro 'AV MARGINAL DIREITA DO TIETE' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'AV VITOR MANZINI' na subprefeitura 'SANTO-AMARO'
Refinado para 'LIBERDADE' para logradouro 'R GLICERIO' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV SANTOS DUMONT' na subprefeitura 'SE'
Refinado para 'BELA VISTA' para logradouro 'AV PAULISTA' na subprefeitura 'SE'
Refinado para 'SE' para logradouro 'AV PRES CASTELO BRANCO' na subprefeitura 'SE'
Refinado para 'VILA FORMOSA' para logradouro 'AV DR EDUARDO COTCHING' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=R+TIERS%2C+TATUAPE%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Refinado para 'PARI' para logradouro 'R TIERS' na subprefeitura 'MOOCA'
Refinado para 'MOOCA' para logradouro 'AV ALCANTARA MACHADO' na subprefeitura 'MOOCA'
Refinado para 'AGUA RASA' para logradouro 'R SALIM FARAH MALUF' na subprefeitura 'MOOCA'
Refinado para 'BRAS' para logradouro 'AV CELSO GARCIA' na subprefeitura 'MOOCA'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=R+MELO+FREIRE%2C+BRAS%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Refinado para 'BRAS' para logradouro 'R MELO FREIRE' na subprefeitura 'MOOCA'
Refinado para 'PARI' para logradouro 'R BRESSER' na subprefeitura 'MOOCA'
Refinado para 'TATUAPE' para logradouro 'AV CDSSA ELISABETH DE ROBIANO' na subprefeitura 'MOOCA'
Refinado para 'VILA PRUDENTE' para logradouro 'AV PROF LUIZ IGNACIO ANHAIA MELLO' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'R SALIM FARAH MALUF' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'AV PROF LUIZ IGNACIO ANHAIA MELLO' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'R AMERICO VESPUCCI' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'LIMAO' para logradouro 'AV ANTONIO MUNHOZ BONILHA' na subprefeitura 'CASA-VERDE'
Refinado para 'CASA VERDE' para logradouro 'AV ORDEM E PROGRESSO' na subprefeitura 'CASA-VERDE'
Refinado para 'JACANA' para logradouro 'AV EDU CHAVES' na subprefeitura 'JACANA-TREMEMBE'
Refinado para 'VILA MARIA' para logradouro 'AV MORVAN DIAS DE FIGUEIREDO' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'VILA MARIA' para logradouro 'AV MORVAN DIAS DE FIGUEIREDO' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'VILA MARIA' para logradouro 'AV MORVAN DIAS DE FIGUEIREDO' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'MORUMBI' para logradouro 'R SERGIO PAULO FREDDI' na subprefeitura 'BUTANTA'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=AV+VITAL+BRAZIL%2C+BUTANTA%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV VITAL BRAZIL' na subprefeitura 'BUTANTA'
Refinado para 'BARRA FUNDA' para logradouro 'AV ANTARTICA' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'AV MARQ DE SAO VICENTE' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'AV MARQ DE SAO VICENTE' na subprefeitura 'LAPA'
Refinado para 'BARRA FUNDA' para logradouro 'R TAGIPURU' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'AV MARQ DE SAO VICENTE' na subprefeitura 'LAPA'
Refinado para 'BARRA FUNDA' para logradouro 'AV PRES CASTELO BRANCO' na subprefeitura 'LAPA'
Refinado para 'PINHEIROS' para logradouro 'R ABEGOARIA' na subprefeitura 'PINHEIROS'
Refinado para 'ITAIM BIBI' para logradouro 'TN MAX FEFFER' na subprefeitura 'PINHEIROS'
Refinado para 'CAMPO GRANDE' para logradouro 'AV SANTO AMARO' na subprefeitura 'SANTO-AMARO'
Refinado para 'MORUMBI' para logradouro 'AV LINEU DE PAULA MACHADO' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'PINHEIROS' para logradouro 'AV EUSEBIO MATOSO' na subprefeitura 'PINHEIROS'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AV DRA RUTH CARDOSO' na subprefeitura 'PINHEIROS'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AV DRA RUTH CARDOSO' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'SAUDE' para 'CV JOAO JORGE SAAD' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'SOCORRO' para logradouro 'AV GUARAPIRANGA' na subprefeitura 'CAPELA-DO-SOCORRO'
Refinado para 'CASA VERDE' para logradouro 'R REIMS' na subprefeitura 'CASA-VERDE'
Não foi possível refinar para um distrito único, usando o primeiro: 'SANTANA' para 'PTE DAS BANDEIRAS SEN ROMEU TUMA' na subprefeitura 'SANTANA'
Refinado para 'BUTANTA' para logradouro 'R MONCORVO FILHO' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'AV MARQ DE SAO VICENTE' na subprefeitura 'LAPA'
Refinado para 'GUAIANASES' para logradouro 'RUA ALEXANDRE LEGRAND' na subprefeitura 'GUAIANASES'
Refinado para 'PARI' para logradouro 'AV CRUZEIRO DO SUL' na subprefeitura 'MOOCA'
Refinado para 'MOOCA' para logradouro 'AV ALCANTARA MACHADO' na subprefeitura 'MOOCA'
Não foi possível refinar para um distrito único, usando o primeiro: 'VILA MARIA' para 'AV EDUC PAULO FREIRE' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'AV COMEN MARTINELLI' na subprefeitura 'LAPA'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CAPAO REDONDO' para logradouro 'AV ELLIS MAAS' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'JARDIM SAO LUIS' para logradouro 'AV JOAO DIAS' na subprefeitura 'M-BOI-MIRIM'
Refinado para 'CAMPO GRANDE' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'SANTO-AMARO'
Refinado para 'CAMPO GRANDE' para logradouro 'AV STO AMARO' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'AV VITOR MANZINI' na subprefeitura 'SANTO-AMARO'
Refinado para 'VILA PRUDENTE' para logradouro 'AV VILA EMA' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'AV PROF LUIZ IGNACIO ANHAIA MELLO' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'R SALIM FARAH MALUF' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'R IBITIRAMA' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'AV PROF LUIZ IGNACIO ANHAIA MELLO' na subprefeitura 'VILA-PRUDENTE'
Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV VITAL BRAZIL' na subprefeitura 'BUTANTA'
Refinado para 'IPIRANGA' para logradouro 'AV DO ESTADO' na subprefeitura 'IPIRANGA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'VD JOSE COLASUONNO' na subprefeitura 'IPIRANGA'
Refinado para 'MOEMA' para logradouro 'AV PEDRO ALVARES CABRAL' na subprefeitura 'VILA-MARIANA'
Refinado para 'SAUDE' para logradouro 'AV PROF ABRAAO DE MORAIS' na subprefeitura 'VILA-MARIANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'AC A AV DAS NACOES UNIDAS CAMPO GRANDE' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'PC DOM FRANCISCO DE SOUSA' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'RUA JORGE DUPRAT' na subprefeitura 'SANTO-AMARO'
Refinado para 'CAMPO GRANDE' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'SANTO-AMARO'
Refinado para 'CAMPO GRANDE' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'SANTO-AMARO'
Refinado para 'VILA FORMOSA' para logradouro 'AV REG FEIJO' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'MOOCA' para logradouro 'AV ALCANTARA MACHADO' na subprefeitura 'MOOCA'
Refinado para 'BRAS' para logradouro 'R MELO FREIRE' na subprefeitura 'MOOCA'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=VD+PIRES+DO+RIO%2C+BELEM%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Não foi possível refinar para um distrito único, usando o primeiro: 'AGUA RASA' para 'VD PIRES DO RIO' na subprefeitura 'MOOCA'
Refinado para 'TATUAPE' para logradouro 'R ARNALDO CINTRA' na subprefeitura 'MOOCA'
Não foi possível refinar para um distrito único, usando o primeiro: 'AGUA RASA' para 'AV CD DE FRONTIN' na subprefeitura 'MOOCA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'AV CD DE FRONTIN' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'VILA PRUDENTE' para 'AV EDU CHAVES' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'AV VILA EMA' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'AV SALIM FARAH MALUF' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'AV FRANCISCO FALCONI' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'R ARACATI-MIRIM' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'VILA PRUDENTE' para logradouro 'AV PROF LUIZ IGNACIO ANHAIA MELLO' na subprefeitura 'VILA-PRUDENTE'
Refinado para 'SANTANA' para logradouro 'AV ZAKI NARCHI' na subprefeitura 'SANTANA'
Refinado para 'VILA MEDEIROS' para logradouro 'AV EDU CHAVES' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'BELA VISTA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'SE'
Refinado para 'SE' para logradouro 'AV PRES CASTELO BRANCO' na subprefeitura 'SE'
Refinado para 'BELA VISTA' para logradouro 'TN S JOAO PAULO II' na subprefeitura 'SE'
Refinado para 'BELA VISTA' para logradouro 'PC DA BANDEIRA' na subprefeitura 'SE'
Refinado para 'VILA FORMOSA' para logradouro 'R ARNALDO ROSA' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'PARI' para logradouro 'R TIERS' na subprefeitura 'MOOCA'
Refinado para 'BRAS' para logradouro 'AV CELSO GARCIA' na subprefeitura 'MOOCA'
Refinado para 'SANTANA' para logradouro 'AV OLAVO FONTOURA' na subprefeitura 'SANTANA'
Refinado para 'SANTANA' para logradouro 'AV OLAVO FONTOURA' na subprefeitura 'SANTANA'
Refinado para 'VILA MARIA' para logradouro 'AV MORVAN DIAS DE FIGUEIREDO' na subprefeitura 'VILA-MARIA-VILA-GUILHERME'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'ITAIM BIBI' para logradouro 'MARGINAL PINHEIROS INTCB' na subprefeitura 'PINHEIROS'
Refinado para 'ALTO DE PINHEIROS' para logradouro 'AV DRA RUTH CARDOSO' na subprefeitura 'PINHEIROS'
Refinado para 'JARDIM PAULISTA' para logradouro 'R COLOMBIA' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'R PRES BATISTA PEREIRA' na subprefeitura 'IPIRANGA'
Refinado para 'SOCORRO' para logradouro 'AV GUARAPIRANGA' na subprefeitura 'CAPELA-DO-SOCORRO'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'AV VITOR MANZINI' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'AV VITOR MANZINI' na subprefeitura 'SANTO-AMARO'
Refinado para 'ITAIM PAULISTA' para logradouro 'R RAFAEL CORREIA DA SILVA' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'VILA CURUCA' para 'RUA MARIA LAZZARI' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'RUA ITAJUIBE' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV CORREGO TIJUCO PRETO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'JARDIM HELENA' para logradouro 'RUA CORDAO DE SAO FRANCISCO' na subprefeitura 'SAO-MIGUEL-PAULISTA'
Refinado para 'MOOCA' para logradouro 'AV ALCANTARA MACHADO' na subprefeitura 'MOOCA'
Refinado para 'ITAIM BIBI' para logradouro 'AV STO AMARO' na subprefeitura 'PINHEIROS'
Refinado para 'VILA MARIANA' para logradouro 'AV DR RICARDO JAFET' na subprefeitura 'VILA-MARIANA'
Refinado para 'CIDADE ADEMAR' para logradouro 'AV INTERLAGOS' na subprefeitura 'CIDADE-ADEMAR'
Refinado para 'CAMPO GRANDE' para logradouro 'AV STO AMARO' na subprefeitura 'SANTO-AMARO'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO GRANDE' para 'AV VITOR MANZINI' na subprefeitura 'SANTO-AMARO'
Refinado para 'SANTANA' para logradouro 'AV ZAKI NARCHI' na subprefeitura 'SANTANA'
Refinado para 'VILA LEOPOLDINA' para logradouro 'AV QUEIROZ FILHO' na subprefeitura 'LAPA'
Refinado para 'VILA LEOPOLDINA' para logradouro 'PC APECATU' na subprefeitura 'LAPA'
Refinado para 'GUAIANASES' para logradouro 'RUA ALEXANDRE LEGRAND' na subprefeitura 'GUAIANASES'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAQUERA' para logradouro 'RUA CUNHA PORA' na subprefeitura 'ITAQUERA'
Refinado para 'PENHA' para logradouro 'AV AIRTON PRETINI' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'R FREI BERTOLDO' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'VILA PRUDENTE' para 'AV VILA EMMA' na subprefeitura 'VILA-PRUDENTE'
Não foi possível refinar para um distrito único, usando o primeiro: 'LIMAO' para 'AV NSRA DO O' na subprefeitura 'CASA-VERDE'
Não foi possível refinar para um distrito único, usando o primeiro: 'LIMAO' para 'AV NSRA DO O' na subprefeitura 'CASA-VERDE'
Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV VITAL BRAZIL' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'LAPA' para logradouro 'R CORIOLANO' na subprefeitura 'LAPA'
Refinado para 'BARRA FUNDA' para logradouro 'PC PASCOAL MARTINS' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'SAUDE' para 'CV TRIBUNAL DE JUSTICA DO E SP' na subprefeitura 'VILA-MARIANA'
Refinado para 'VILA MARIANA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'VILA-MARIANA'
Refinado para 'MOEMA' para logradouro 'PC JUCA MULATO' na subprefeitura 'VILA-MARIANA'
Refinado para 'MOEMA' para logradouro 'R DR HABERBECK BRANDAO' na subprefeitura 'VILA-MARIANA'
Refinado para 'MOEMA' para logradouro 'PC JUCA MULATO' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CAMPO GRANDE' para logradouro 'AV INTERLAGOS' na subprefeitura 'SANTO-AMARO'
Refinado para 'GUAIANASES' para logradouro 'RUA ALEXANDRE LEGRAND' na subprefeitura 'GUAIANASES'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAQUERA' para logradouro 'AV ITAQUERA' na subprefeitura 'ITAQUERA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CIDADE LIDER' para 'R PDE VIEGAS DE MENEZES' na subprefeitura 'ITAQUERA'
Refinado para 'ITAQUERA' para logradouro 'RUA CUNHA PORA' na subprefeitura 'ITAQUERA'
Refinado para 'PARI' para logradouro 'R BRESSER' na subprefeitura 'MOOCA'
Refinado para 'JARDIM HELENA' para logradouro 'R BERNARDO DE CHAVES CABRAL' na subprefeitura 'SAO-MIGUEL-PAULISTA'
Refinado para 'SAO MIGUEL' para logradouro 'AV S MIGUEL' na subprefeitura 'SAO-MIGUEL-PAULISTA'
Refinado para 'LAPA' para logradouro 'R VENANCIO AIRES' na subprefeitura 'LAPA'
Refinado para 'BARRA FUNDA' para logradouro 'AV POMPEIA' na subprefeitura 'LAPA'
Refinado para 'VILA MARIANA' para logradouro 'AV DR RICARDO JAFET' na subprefeitura 'VILA-MARIANA'
Refinado para 'ARTUR ALVIM' para logradouro 'R DR LUIZ AYRES' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'IGUATEMI' para 'AV JACU PESSEGO N TRABALHADORES' na subprefeitura 'SAO-MATEUS'
Refinado para 'BELA VISTA' para logradouro 'R MANOEL DUTRA' na subprefeitura 'SE'
Refinado para 'LIBERDADE' para logradouro 'R S PAULO LIBERDADE' na subprefeitura 'SE'
Refinado para 'BELA VISTA' para logradouro 'PC DA BANDEIRA' na subprefeitura 'SE'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CURSINO' para 'R PRES BATISTA PEREIRA' na subprefeitura 'IPIRANGA'
Refinado para 'VILA MARIANA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'VILA-MARIANA'
Refinado para 'VILA MARIANA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'VILA-MARIANA'
Refinado para 'BOM RETIRO' para logradouro 'AV RIO BRANCO' na subprefeitura 'SE'
Refinado para 'ITAQUERA' para logradouro 'R DAMASIO PINTO' na subprefeitura 'ITAQUERA'
Refinado para 'BRAS' para logradouro 'AV CELSO GARCIA' na subprefeitura 'MOOCA'
Refinado para 'PARI' para logradouro 'R BRESSER' na subprefeitura 'MOOCA'
Refinado para 'CAPAO REDONDO' para logradouro 'AV ELLIS MAAS' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'PIRITUBA' para logradouro 'AV BENEDITO ANDRADE' na subprefeitura 'PIRITUBA-JARAGUA'
Refinado para 'PIRITUBA' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'PIRITUBA-JARAGUA'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARAGUA' para 'MARGINAL TIETE ASCB EXPRESSA' na subprefeitura 'PIRITUBA-JARAGUA'
Refinado para 'SANTANA' para logradouro 'AV AVENIDA CRUZEIRO DO SUL' na subprefeitura 'SANTANA'
Refinado para 'MORUMBI' para logradouro 'AV PROF FRANCISCO MORATO' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'MARGINAL TIETE CBAS CENTRAL' na subprefeitura 'LAPA'
Refinado para 'VILA FORMOSA' para logradouro 'AV REG FEIJO' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'VILA FORMOSA' para logradouro 'AV REG FEIJO' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'R PDE COSTA' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CANGAIBA' para 'R FREI BERTOLDO' na subprefeitura 'PENHA'
Não foi possível refinar para um distrito único, usando o primeiro: 'BARRA FUNDA' para 'MARGINAL TIETE CBAS EXPRESSA' na subprefeitura 'LAPA'
Refinado para 'BOM RETIRO' para logradouro 'AV SANTOS DUMONT' na subprefeitura 'SE'
Refinado para 'PARI' para logradouro 'AV CRUZEIRO DO SUL' na subprefeitura 'MOOCA'

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=R+PEDRO+VICENTE%2C+AGUA+RASA%2C+S%C3%A3o+Paulo%2C+Brazil&format=json&limit=1

Refinado para 'PARI' para logradouro 'R PEDRO VICENTE' na subprefeitura 'MOOCA'
Refinado para 'SANTANA' para logradouro 'MARGINAL TIETE ASCB CENTRAL' na subprefeitura 'SANTANA'
Refinado para 'SANTANA' para logradouro 'AV CRUZEIRO DO SUL' na subprefeitura 'SANTANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV VITAL BRAZIL' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'R ALVARENGA' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'CAMPO LIMPO' para logradouro 'AV CARLOS CALDEIRA FILHO' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'MORUMBI' para logradouro 'AV GIOVANI GRONCHI' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV PROF FRANCISCO MORATO' na subprefeitura 'BUTANTA'
Refinado para 'JARDIM PAULISTA' para logradouro 'R ARGENTINA' na subprefeitura 'PINHEIROS'
Refinado para 'VILA MARIANA' para logradouro 'AV VINTE E TRES DE MAIO' na subprefeitura 'VILA-MARIANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARDIM ANGELA' para 'ES DE ITAPECERICA' na subprefeitura 'M-BOI-MIRIM'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARDIM ANGELA' para 'ES M BOI MIRIM' na subprefeitura 'M-BOI-MIRIM'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MARECHAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'ITAIM PAULISTA' para logradouro 'AV MAL TITO' na subprefeitura 'ITAIM-PAULISTA'
Refinado para 'MOOCA' para logradouro 'R HIPODROMO' na subprefeitura 'MOOCA'
Refinado para 'PARI' para logradouro 'R BRESSER' na subprefeitura 'MOOCA'
Não foi possível refinar para um distrito único, usando o primeiro: 'JARAGUA' para 'MARGINAL TIETE ASCB EXPRESSA' na subprefeitura 'PIRITUBA-JARAGUA'
Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV ENG BILLINGS' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'AV JULES RIMET' na subprefeitura 'BUTANTA'
Refinado para 'CAPAO REDONDO' para logradouro 'AV ELLIS MAAS' na subprefeitura 'CAMPO-LIMPO'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO LIMPO' para 'AV ELIS MAAS 940' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CAPAO REDONDO' para logradouro 'R INTEGRADA' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'CIDADE ADEMAR' para logradouro 'AV INTERLAGOS' na subprefeitura 'CIDADE-ADEMAR'
Refinado para 'CAMPO BELO' para logradouro 'RUA MONSENHOR NALINE' na subprefeitura 'SANTO-AMARO'
Refinado para 'CAMPO GRANDE' para logradouro 'AV STO AMARO' na subprefeitura 'SANTO-AMARO'
Refinado para 'VILA FORMOSA' para logradouro 'AV REG FEIJO' na subprefeitura 'ARICANDUVA-VILA-FORMOSA'
Refinado para 'LIMAO' para logradouro 'MARGINAL TIETE ASCB EXPRESSA' na subprefeitura 'CASA-VERDE'
Refinado para 'GUAIANASES' para logradouro 'RUA ALEXANDRE LEGRAND' na subprefeitura 'GUAIANASES'
Refinado para 'ITAQUERA' para logradouro 'AV ITAQUERA' na subprefeitura 'ITAQUERA'
Refinado para 'ITAQUERA' para logradouro 'AV JOSE PINHEIRO BORGES' na subprefeitura 'ITAQUERA'
Refinado para 'AGUA RASA' para logradouro 'AV VILA EMA' na subprefeitura 'MOOCA'
Refinado para 'SANTANA' para logradouro 'AV MORVAN DIAS DE FIGUEIREDO' na subprefeitura 'SANTANA'
Não foi possível refinar para um distrito único, usando o primeiro: 'MORUMBI' para 'AV VITAL BRAZIL' na subprefeitura 'BUTANTA'
Refinado para 'MORUMBI' para logradouro 'R ALVARENGA' na subprefeitura 'BUTANTA'
Refinado para 'PINHEIROS' para logradouro 'AV DAS NACOES UNIDAS' na subprefeitura 'PINHEIROS'
Refinado para 'ITAIM BIBI' para logradouro 'TN MAX FEFFER' na subprefeitura 'PINHEIROS'
Não foi possível refinar para um distrito único, usando o primeiro: 'ALTO DE PINHEIROS' para 'TN JORN FERNANDO VIEIRA DE MELLO' na subprefeitura 'PINHEIROS'
Refinado para 'IPIRANGA' para logradouro 'RUA DAS JUNTAS PROVISORIAS' na subprefeitura 'IPIRANGA'
Refinado para 'CURSINO' para logradouro 'AV ABRAAO DE MORAIS' na subprefeitura 'IPIRANGA'
Refinado para 'IPIRANGA' para logradouro 'AV TERESA CRISTINA' na subprefeitura 'IPIRANGA'
Refinado para 'SAUDE' para logradouro 'AV PROF ABRAAO DE MORAIS' na subprefeitura 'VILA-MARIANA'
Refinado para 'CAMPO BELO' para logradouro 'RUA MONSENHOR NALINE' na subprefeitura 'SANTO-AMARO'
Refinado para 'CASA VERDE' para logradouro 'AV OTAVIANO ALVES DE LIMA' na subprefeitura 'CASA-VERDE'
Refinado para 'BELA VISTA' para logradouro 'PC DA BANDEIRA' na subprefeitura 'SE'
Refinado para 'BOM RETIRO' para logradouro 'AV SANTOS DUMONT' na subprefeitura 'SE'
Refinado para 'MOOCA' para logradouro 'AV ALCANTARA MACHADO' na subprefeitura 'MOOCA'
Refinado para 'PARI' para logradouro 'R PEDRO VICENTE' na subprefeitura 'MOOCA'
Refinado para 'SANTANA' para logradouro 'AV ZAKI NARCHI' na subprefeitura 'SANTANA'
Refinado para 'BARRA FUNDA' para logradouro 'PC PASCOAL MARTINS' na subprefeitura 'LAPA'
Não foi possível refinar para um distrito único, usando o primeiro: 'CAMPO LIMPO' para 'AV ELIS MAAS 940' na subprefeitura 'CAMPO-LIMPO'
Refinado para 'BOM RETIRO' para logradouro 'R BARRA DO TIBAGI' na subprefeitura 'SE'
DataFrame 'df_alagamentos_cge' após preencher e refinar a coluna 'distrito':

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia,distrito
0,2025-03-28,Zona Leste,ITAIM-PAULISTA,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557,ITAIM PAULISTA
1,2025-03-28,Zona Norte,VILA-MARIA-VILA-GUILHERME,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661,VILA MEDEIROS
2,2025-03-28,Zona Oeste,PINHEIROS,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0,ALTO DE PINHEIROS
3,2025-03-28,Zona Sudeste,IPIRANGA,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52,CURSINO
4,2025-03-31,Zona Leste,ITAQUERA,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843,CIDADE LIDER

### Gerando Colunas de Latitude e Longitude

In [282]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# Re-inicializa o geocodificador Nominatim com um timeout de 5 segundos para coordenadas
geolocator = Nominatim(user_agent="geo_flooding_analysis", timeout=5)

# Adiciona um limitador de taxa para evitar bloqueios da API (1 requisição por segundo)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

print("Geocodificador Nominatim reconfigurado com timeout de 5 segundos para latitude/longitude.")

Geocodificador Nominatim reconfigurado com timeout de 5 segundos para latitude/longitude.

In [ ]:
def get_coordinates_from_address(row):
    logradouro = row['logradouro']
    referencia = row['referencia']
    distrito = row['distrito'] # 'distrito' deve ser um único distrito ou None

    # Prioriza o primeiro distrito se houver múltiplos separados por vírgula
    single_distrito = None
    if isinstance(distrito, str) and distrito:
        single_distrito = distrito.split(',')[0].strip()

    # Tenta geocodificar apenas pelo distrito primeiro para maior chance de sucesso
    if single_distrito:
        query_distrito_only = f"{single_distrito}, São Paulo, Brazil"
        try:
            location_distrito = geocode(query_distrito_only)
            if location_distrito:
                print(f"Coordenadas encontradas (apenas distrito) para '{query_distrito_only}': ({location_distrito.latitude}, {location_distrito.longitude})")
                return location_distrito.latitude, location_distrito.longitude
            else:
                print(f"Não foi possível encontrar coordenadas (apenas distrito) para '{query_distrito_only}'")
        except Exception as e:
            print(f"Erro ao geocodificar (apenas distrito) '{query_distrito_only}': {e}")

    # Se falhou com apenas o distrito, tenta a query mais específica (logradouro + referencia + distrito)
    address_parts_full = [logradouro]
    if referencia != 0:
        address_parts_full.append(str(referencia))
    if single_distrito:
        address_parts_full.append(single_distrito)
    address_parts_full.append('São Paulo')
    address_parts_full.append('Brazil')

    query_full = ', '.join(address_parts_full)

    try:
        location_full = geocode(query_full)
        if location_full:
            print(f"Coordenadas encontradas (completa) para '{query_full}': ({location_full.latitude}, {location_full.longitude})")
            return location_full.latitude, location_full.longitude
        else:
            print(f"Não foi possível encontrar coordenadas (completa) para '{query_full}'")
            return np.nan, np.nan
    except Exception as e:
        print(f"Erro ao geocodificar (completa) '{query_full}': {e}")
        return np.nan, np.nan

# Aplica a função para criar as colunas de latitude e longitude
df_alagamentos_cge[['latitude', 'longitude']] = df_alagamentos_cge.apply(lambda row: pd.Series(get_coordinates_from_address(row)), axis=1)

print("DataFrame 'df_alagamentos_cge' após adicionar as colunas de latitude e longitude:")
display(df_alagamentos_cge.head())
print("Tipos de dados das novas colunas:")
print(df_alagamentos_cge[['latitude', 'longitude']].dtypes)

Coordenadas encontradas (apenas distrito) para 'ITAIM PAULISTA, São Paulo, Brazil': (-23.5017648, -46.3996091)
Coordenadas encontradas (apenas distrito) para 'VILA MEDEIROS, São Paulo, Brazil': (-23.487707, -46.5844955)
Coordenadas encontradas (apenas distrito) para 'ALTO DE PINHEIROS, São Paulo, Brazil': (-23.5499064, -46.7076422)
Coordenadas encontradas (apenas distrito) para 'CURSINO, São Paulo, Brazil': (-23.6276481, -46.6193408)
Coordenadas encontradas (apenas distrito) para 'CIDADE LIDER, São Paulo, Brazil': (-23.5627696, -46.4943334)
Coordenadas encontradas (apenas distrito) para 'AGUA RASA, São Paulo, Brazil': (-23.5653715, -46.5736972)
Coordenadas encontradas (apenas distrito) para 'VILA PRUDENTE, São Paulo, Brazil': (-23.5845945, -46.5834369)
Coordenadas encontradas (apenas distrito) para 'MORUMBI, São Paulo, Brazil': (-23.5974288, -46.7067746)
Coordenadas encontradas (apenas distrito) para 'ALTO DE PINHEIROS, São Paulo, Brazil': (-23.5499064, -46.7076422)
Coordenadas encontradas (apenas distrito) para 'ALTO DE PINHEIROS, São Paulo, Brazil': (-23.5499064, -46.7076422)
Coordenadas encontradas (apenas distrito) para 'IPIRANGA, São Paulo, Brazil': (-23.5892725, -46.6061621)
Coordenadas encontradas (apenas distrito) para 'IPIRANGA, São Paulo, Brazil': (-23.5892725, -46.6061621)
Coordenadas encontradas (apenas distrito) para 'CURSINO, São Paulo, Brazil': (-23.6276481, -46.6193408)
Coordenadas encontradas (apenas distrito) para 'ALTO DE PINHEIROS, São Paulo, Brazil': (-23.5499064, -46.7076422)
Coordenadas encontradas (apenas distrito) para 'IGUATEMI, São Paulo, Brazil': (-23.6181809, -46.418994)
Coordenadas encontradas (apenas distrito) para 'BOM RETIRO, São Paulo, Brazil': (-23.5251634, -46.6381644)
Coordenadas encontradas (apenas distrito) para 'BELA VISTA, São Paulo, Brazil': (-23.5601219, -46.6500338)
Coordenadas encontradas (apenas distrito) para 'BELA VISTA, São Paulo, Brazil': (-23.5601219, -46.6500338)
Coordenadas encontradas (apenas distrito) para 'JACANA, São Paulo, Brazil': (-23.4629935, -46.582443)
Coordenadas encontradas (apenas distrito) para 'JACANA, São Paulo, Brazil': (-23.4629935, -46.582443)
Coordenadas encontradas (apenas distrito) para 'SANTANA, São Paulo, Brazil': (-22.004508, -50.3862746)
Coordenadas encontradas (apenas distrito) para 'SANTANA, São Paulo, Brazil': (-22.004508, -50.3862746)
Coordenadas encontradas (apenas distrito) para 'BOM RETIRO, São Paulo, Brazil': (-23.5251634, -46.6381644)
Coordenadas encontradas (apenas distrito) para 'VILA FORMOSA, São Paulo, Brazil': (-23.5668764, -46.5463233)
Coordenadas encontradas (apenas distrito) para 'ITAQUERA, São Paulo, Brazil': (-23.5422994, -46.4712065)
Coordenadas encontradas (apenas distrito) para 'CIDADE LIDER, São Paulo, Brazil': (-23.5627696, -46.4943334)
Coordenadas encontradas (apenas distrito) para 'RAPOSO TAVARES, São Paulo, Brazil': (-23.5917093, -46.7805123)
Coordenadas encontradas (apenas distrito) para 'JARDIM ANGELA, São Paulo, Brazil': (-23.7125278, -46.7687195)
Coordenadas encontradas (apenas distrito) para 'BELA VISTA, São Paulo, Brazil': (-23.5601219, -46.6500338)
Coordenadas encontradas (apenas distrito) para 'BOM RETIRO, São Paulo, Brazil': (-23.5251634, -46.6381644)
Coordenadas encontradas (apenas distrito) para 'SE, São Paulo, Brazil': (-23.5504428, -46.6334463)
Coordenadas encontradas (apenas distrito) para 'GUAIANASES, São Paulo, Brazil': (-23.5522554, -46.4069533)
Coordenadas encontradas (apenas distrito) para 'ITAIM PAULISTA, São Paulo, Brazil': (-23.5017648, -46.3996091)
Coordenadas encontradas (apenas distrito) para 'ITAIM PAULISTA, São Paulo, Brazil': (-23.5017648, -46.3996091)
Coordenadas encontradas (apenas distrito) para 'CASA VERDE, São Paulo, Brazil': (-23.5059269, -46.6561379)
Coordenadas encontradas (apenas distrito) para 'CASA VERDE, São Paulo, Brazil': (-23.5059269, -46.6561379)
Coordenadas encontradas (apenas distrito) para 'SANTANA, São Paulo, Brazil': (-22.004508, -50.3862746)
Coordenadas encontradas (apenas distrito) para 'BARRA FUNDA, São Paulo, Brazil': (-23.5254616, -46.6675134)
Coordenadas encontradas (apenas distrito) para 'BARRA FUNDA, São Paulo, Brazil': (-23.5254616, -46.6675134)
Coordenadas encontradas (apenas distrito) para 'IGUATEMI, São Paulo, Brazil': (-23.6181809, -46.418994)
Coordenadas encontradas (apenas distrito) para 'CANGAIBA, São Paulo, Brazil': (-23.5058996, -46.5314253)
Coordenadas encontradas (apenas distrito) para 'BARRA FUNDA, São Paulo, Brazil': (-23.5254616, -46.6675134)
Coordenadas encontradas (apenas distrito) para 'BRAS, São Paulo, Brazil': (-23.5451136, -46.6163355)
Coordenadas encontradas (apenas distrito) para 'SAPOPEMBA, São Paulo, Brazil': (-23.6043265, -46.5098851)
Coordenadas encontradas (apenas distrito) para 'BOM RETIRO, São Paulo, Brazil': (-23.5251634, -46.6381644)
Coordenadas encontradas (apenas distrito) para 'ITAIM PAULISTA, São Paulo, Brazil': (-23.5017648, -46.3996091)
Coordenadas encontradas (apenas distrito) para 'ITAQUERA, São Paulo, Brazil': (-23.5422994, -46.4712065)
Coordenadas encontradas (apenas distrito) para 'ALTO DE PINHEIROS, São Paulo, Brazil': (-23.5499064, -46.7076422)
Coordenadas encontradas (apenas distrito) para 'ARTUR ALVIM, São Paulo, Brazil': (-23.5402438, -46.4847063)
Coordenadas encontradas (apenas distrito) para 'CASA VERDE, São Paulo, Brazil': (-23.5059269, -46.6561379)
Coordenadas encontradas (apenas distrito) para 'MORUMBI, São Paulo, Brazil': (-23.5974288, -46.7067746)
Coordenadas encontradas (apenas distrito) para 'MORUMBI, São Paulo, Brazil': (-23.5974288, -46.7067746)
Coordenadas encontradas (apenas distrito) para 'SE, São Paulo, Brazil': (-23.5504428, -46.6334463)
Coordenadas encontradas (apenas distrito) para 'ARICANDUVA, São Paulo, Brazil': (-23.5780239, -46.511454)

In [286]:
display(df_alagamentos_cge)

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia,distrito,latitude,longitude
0,2025-03-28,Zona Leste,ITAIM-PAULISTA,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557,ITAIM PAULISTA,-23.501765,-46.399609
1,2025-03-28,Zona Norte,VILA-MARIA-VILA-GUILHERME,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661,VILA MEDEIROS,-23.487707,-46.584496
2,2025-03-28,Zona Oeste,PINHEIROS,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0,ALTO DE PINHEIROS,-23.549906,-46.707642
3,2025-03-28,Zona Sudeste,IPIRANGA,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52,CURSINO,-23.627648,-46.619341
4,2025-03-31,Zona Leste,ITAQUERA,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843,CIDADE LIDER,-23.562770,-46.494333
...,...,...,...,...,...,...,...,...,...,...,...,...
485,2026-03-19,Zona Leste,MOOCA,Inativo Transitável,12:57,13:19,R PEDRO VICENTE,UNICO,0,PARI,-23.532976,-46.615849
486,2026-03-19,Zona Norte,SANTANA,Inativo Transitável,12:33,12:50,AV ZAKI NARCHI,AMBOS,0,SANTANA,-22.004508,-50.386275
487,2026-03-19,Zona Oeste,LAPA,Inativo Intransitável,12:33,14:25,PC PASCOAL MARTINS,UNICO,0,BARRA FUNDA,-23.525462,-46.667513
488,2026-03-19,Zona Sul,CAMPO-LIMPO,Inativo Intransitável,14:30,14:53,AV ELIS MAAS 940,AMBOS,0,CAMPO LIMPO,-23.636200,-46.762797
489,2026-03-26,Centro,SE,Inativo Transitável,15:35,16:10,R BARRA DO TIBAGI,UNICO,544,BOM RETIRO,-23.525163,-46.638164

In [287]:
# Converte a coluna 'data' para o tipo datetime, se ainda não estiver
df_alagamentos_cge['data'] = pd.to_datetime(df_alagamentos_cge['data'])

# Combina 'data' com 'hora_inicio' para criar 'dt_hr_inicio'
df_alagamentos_cge['dt_hr_inicio'] = df_alagamentos_cge.apply(lambda row: pd.to_datetime(f"{row['data'].date()} {row['hora_inicio']}"), axis=1)

# Combina 'data' com 'hora_fim' para criar 'dt_hr_fim'
df_alagamentos_cge['dt_hr_fim'] = df_alagamentos_cge.apply(lambda row: pd.to_datetime(f"{row['data'].date()} {row['hora_fim']}"), axis=1)

# Reordena as colunas para colocar as novas colunas ao lado de 'data'
cols = df_alagamentos_cge.columns.tolist()
insert_idx = cols.index('data') + 1
cols.insert(insert_idx, 'dt_hr_inicio')
cols.insert(insert_idx + 1, 'dt_hr_fim')
cols.remove('dt_hr_inicio') # Remove as duplicatas antes de reatribuir
cols.remove('dt_hr_fim') # Remove as duplicatas antes de reatribuir

df_alagamentos_cge = df_alagamentos_cge[cols]

print("DataFrame 'df_alagamentos_cge' após adicionar as colunas 'dt_hr_inicio' e 'dt_hr_fim':")
display(df_alagamentos_cge.head())
print("Tipos de dados das novas colunas:")
print(df_alagamentos_cge[['dt_hr_inicio', 'dt_hr_fim']].dtypes)

DataFrame 'df_alagamentos_cge' após adicionar as colunas 'dt_hr_inicio' e 'dt_hr_fim':

,data,zona,subprefeitura,status,hora_inicio,hora_fim,logradouro,sentido,referencia,distrito,latitude,longitude,dt_hr_inicio,dt_hr_fim
0,2025-03-28,Zona Leste,ITAIM-PAULISTA,Inativo Transitável,16:50,18:30,AV MARECHAL TITO,AMBOS,7557,ITAIM PAULISTA,-23.501765,-46.399609,2025-03-28 16:50:00,2025-03-28 18:30:00
1,2025-03-28,Zona Norte,VILA-MARIA-VILA-GUILHERME,Inativo Transitável,07:22,11:18,AV JULIO BUONO,AMBOS,1661,VILA MEDEIROS,-23.487707,-46.584496,2025-03-28 07:22:00,2025-03-28 11:18:00
2,2025-03-28,Zona Oeste,PINHEIROS,Inativo Transitável,17:40,21:50,R BRIG HAROLDO VELOSO,UNICO,0,ALTO DE PINHEIROS,-23.549906,-46.707642,2025-03-28 17:40:00,2025-03-28 21:50:00
3,2025-03-28,Zona Sudeste,IPIRANGA,Inativo Transitável,19:31,19:37,R MAEST EDMUNDO PERUZZI,CENTRO/BAIRRO,52,CURSINO,-23.627648,-46.619341,2025-03-28 19:31:00,2025-03-28 19:37:00
4,2025-03-31,Zona Leste,ITAQUERA,Inativo Intransitável,16:53,18:00,AV OSVALDO VALLE CORDEIRO,AMBOS,843,CIDADE LIDER,-23.562770,-46.494333,2025-03-31 16:53:00,2025-03-31 18:00:00

Tipos de dados das novas colunas:
dt_hr_inicio    datetime64[ns]
dt_hr_fim       datetime64[ns]
dtype: object

In [289]:
print("Contagem de valores nulos por coluna em 'df_alagamentos_cge':")
display(df_alagamentos_cge.isnull().sum())

Contagem de valores nulos por coluna em 'df_alagamentos_cge':

data             0
zona             0
subprefeitura    0
status           0
hora_inicio      0
hora_fim         0
logradouro       0
sentido          0
referencia       0
distrito         0
latitude         0
longitude        0
dt_hr_inicio     0
dt_hr_fim        0
dtype: int64

In [288]:
# Salva o DataFrame df_alagamentos_cge em um arquivo CSV
output_csv_path = 'alagamentos_cge_raw_to_trusted.csv'
df_alagamentos_cge.to_csv(output_csv_path, index=False)

print(f"DataFrame salvo com sucesso em '{output_csv_path}'")

DataFrame salvo com sucesso em 'alagamentos_cge_raw_to_trusted.csv'